-- preflight.sql
-- PROPOSAL 0154 -- NOT APPROVED FOR PRODUCTION. NOT APPLIED. NOT A PRODUCTION MIGRATION. Sequencing: ... -> 0152 -> 0154 (this) -> 0155 -> 0156; unrelated 0148 -> 0153 or 0157+ (never 0154-0156).
-- READ-ONLY: ONE select statement over catalogs; no data-/schema-changing statement, no transaction control. RESULT: every row INFO or PASS and a final RESULT | PASS row; otherwise the
-- statement RAISES (invalid input syntax for type integer: "PREFLIGHT 0154 FAIL ...") whose text is the complete report.
with rows as (
  select 100 as ord, 'SERVER' as section, 'server_version' as item, 'INFO' as result, current_setting('server_version')::text as detail
  union all select 110, 'PRECONDITION', 'exactly one function named record_unresolved_carrier_record exists in ANY schema and no trusted twin', case when (select count(*) from pg_proc p where p.proname in ('record_unresolved_carrier_record', '_record_unresolved_carrier_record_trusted')) = 1 then 'PASS' else 'FAIL' end, (select count(*)::text from pg_proc p where p.proname in ('record_unresolved_carrier_record', '_record_unresolved_carrier_record_trusted')) || ' matching function(s)'
  union all select 111, 'PRECONDITION', 'identity arguments are exactly the reviewed signature', case when (select pg_get_function_identity_arguments(oid) from pg_proc where oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')) = 'p_organization_id uuid, p_record_type text, p_record_id uuid, p_reason text, p_detail jsonb' then 'PASS' else 'FAIL' end, coalesce((select pg_get_function_identity_arguments(oid) from pg_proc where oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')), 'MISSING')
  union all select 112, 'PRECONDITION', 'owner is not a client role and is usable by the migration operator', case when (select pg_get_userbyid(p.proowner) not in ('anon', 'authenticated', 'service_role', 'authenticator') and pg_has_role(current_user, p.proowner, 'usage') from pg_proc p where p.oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')) then 'PASS' else 'FAIL' end, coalesce((select pg_get_userbyid(p.proowner)::text from pg_proc p where p.oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')), 'MISSING') || ' / operator ' || current_user
  union all select 113, 'PRECONDITION', 'SECURITY DEFINER with the pinned search_path, returns uuid', case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and p.prorettype = 'uuid'::regtype from pg_proc p where p.oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')) then 'PASS' else 'FAIL' end, coalesce((select p.proconfig::text from pg_proc p where p.oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')), 'MISSING')
  union all select 114, 'PRECONDITION', 'body is the reviewed 0130 baseline definition (0154 not yet applied)', case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')) = '25982afd9f6a4da0d2c18b0315a8eec9' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)')), 'MISSING')
  union all select 115, 'PRECONDITION', 'unresolved_carrier_records exists', case when to_regclass('public.unresolved_carrier_records') is not null then 'PASS' else 'FAIL' end, 'catalog'
  union all select 116, 'PRECONDITION', 'authenticated currently holds table-level UPDATE on unresolved_carrier_records (0130 grant; F-15)', case when has_table_privilege('authenticated', 'public.unresolved_carrier_records', 'UPDATE') then 'PASS' else 'FAIL' end, 'catalog'
  union all select 120, 'EXPOSURE (informational; F-05)', 'open exception rows (0154 never touches them)', 'INFO', coalesce((select count(*)::text from public.unresolved_carrier_records where status = 'unresolved'), 'table missing')
  union all select 121, 'EXPOSURE (informational; F-05)', 'default privileges in schema public granting EXECUTE on functions (why REVOKE FROM PUBLIC alone was not enough)', 'INFO', coalesce((select string_agg(pg_get_userbyid(d.defaclrole) || ': ' || d.defaclacl::text, '; ') from pg_default_acl d where d.defaclobjtype = 'f'), '(none)')
  union all select 300 + g.n, 'ACL', g.sig || ': EXECUTE for ' || g.who, 'INFO', case g.who when 'PUBLIC' then (coalesce((select p.proacl is null or exists (select 1 from aclexplode(p.proacl) a where a.grantee = 0 and a.privilege_type = 'EXECUTE') from pg_proc p where p.oid = to_regprocedure(g.sig)), false))::text
                                                              else has_function_privilege(g.who, to_regprocedure(g.sig), 'execute')::text end
  from (values (1, 'public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)', 'anon'), (2, 'public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)', 'authenticated'), (3, 'public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)', 'service_role'), (4, 'public.record_unresolved_carrier_record(uuid,text,uuid,text,jsonb)', 'PUBLIC')) g(n, sig, who) where to_regprocedure(g.sig) is not null
),
verdict as (
  select count(*) filter (where result = 'PASS') as n_pass, count(*) filter (where result = 'FAIL') as n_fail, count(*) filter (where result = 'INFO') as n_info,
         case when count(*) filter (where result = 'FAIL') = 0 and count(*) filter (where result = 'PASS') > 0 then 0
              else ('PREFLIGHT 0154 FAIL: ' || (count(*) filter (where result = 'FAIL'))::text || ' failing check(s). Full report follows.' || E'\n'
                    || string_agg(section || ' | ' || item || ' | ' || result || ' | ' || detail, E'\n' order by ord))::int
         end as gate
  from rows
)
select r.ord, r.section, r.item, r.result, r.detail from rows r cross join verdict v where v.gate = 0
union all
select 9000, 'RESULT', 'PREFLIGHT 0154: live definition is the reviewed baseline', 'PASS', v.n_pass::text || ' checks passed, 0 failed, ' || v.n_info::text || ' informational rows' from verdict v where v.gate = 0
order by 1;
