-- ---------------------------------------------------------------------------
-- Driver Applications: public, no-login employment intake form at
-- /driver-application. Distinct from public.drivers (the internal record a
-- dispatcher manages) -- an application is reviewed by staff and, if
-- approved, converted into a real driver record. Kept as its own table
-- rather than early rows in `drivers` so an applicant never has any of the
-- access, visibility, or lifecycle a real driver record implies.
--
-- SSN gets the exact same treatment as public.drivers.ssn_encrypted (0014
-- PART 2/3): pgp_sym_encrypt with the same driver_pii_key, last-4-only
-- plaintext for masked display, owner/admin-only reveal, and every reveal
-- logged. Submission itself is anonymous (the applicant has no Supabase Auth
-- session), so the insert path is a SECURITY DEFINER function grantable to
-- `anon` -- there is no INSERT policy or grant for anon on the table itself.
-- ---------------------------------------------------------------------------

create type public.driver_application_status as enum (
  'submitted', 'under_review', 'interview', 'approved', 'rejected', 'converted'
);

create table public.driver_applications (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  status public.driver_application_status not null default 'submitted',

  -- Position & availability
  position_applied_for text,
  availability text check (availability in ('full_time', 'part_time', 'otr', 'regional', 'local', 'flexible')),

  -- Personal information
  first_name text not null,
  middle_name text,
  last_name text not null,
  date_of_birth date,
  ssn_encrypted bytea,
  ssn_last4 text,
  phone text,
  email text,
  address_line1 text,
  city text,
  state text,
  postal_code text,

  -- CDL information
  cdl_number text,
  cdl_state text,
  cdl_class text check (cdl_class in ('A', 'B', 'C')),
  cdl_endorsements text,
  cdl_expiry_date date,

  -- Driving experience
  years_of_experience numeric(4, 1),
  equipment_experience text,

  -- Employment history -- an array of {employer, position, start_date,
  -- end_date, reason_for_leaving}, collected by a repeatable client-side
  -- section. jsonb rather than a child table: it's write-once-then-reviewed
  -- content, never queried/filtered on individually.
  employment_history jsonb not null default '[]'::jsonb,

  -- Driving record (self-disclosed; this app has no MVR/background-check
  -- integration, so it never claims to be a verified/pulled record)
  has_been_convicted_of_dui boolean,
  has_had_license_suspended boolean,
  has_had_preventable_accident boolean,
  driving_record_explanation text,

  -- Medical card
  has_valid_medical_card boolean,
  medical_card_expiry_date date,

  -- Uploaded documents -- array of {label, storage_path, file_name,
  -- uploaded_at}. Bucket is private; staff view via short-lived signed URLs
  -- generated server-side (see get_driver_application_document_url below).
  uploaded_documents jsonb not null default '[]'::jsonb,

  -- Emergency contact
  emergency_contact_name text,
  emergency_contact_phone text,

  -- Electronic signature: typed full legal name + explicit certification
  -- checkbox, not a drawn signature pad. Timestamp + submitting IP are
  -- captured as the rest of the "signing" evidence.
  signature_name text not null,
  signature_agreed_at timestamptz not null default now(),
  submitted_from_ip text,

  -- Review workflow
  reviewed_by uuid references public.profiles (id) on delete set null,
  reviewed_at timestamptz,
  review_notes text,
  converted_driver_id uuid references public.drivers (id) on delete set null,

  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_updated_at
  before update on public.driver_applications
  for each row execute function public.set_updated_at();

create index idx_driver_applications_organization_id on public.driver_applications (organization_id);
create index idx_driver_applications_status on public.driver_applications (status);

comment on column public.driver_applications.ssn_encrypted is
  'PGP-symmetric-encrypted with the same driver_pii_key as public.drivers.ssn_encrypted. Never selectable by authenticated directly -- see the column-level revoke below.';
comment on column public.driver_applications.uploaded_documents is
  'Array of {label, storage_path, file_name, uploaded_at}. storage_path points into the private driver-application-documents bucket; only readable via a signed URL generated by get_driver_application_document_url().';

alter table public.driver_applications enable row level security;

create policy driver_applications_select on public.driver_applications
  for select using (
    organization_id = public.current_org_id()
    and public.has_role(array['owner', 'admin', 'dispatcher']::public.org_role[])
  );

-- Staff can update status/review fields, never the PII or the applicant's
-- own submitted answers -- see the column-level grant below, which is the
-- real enforcement (RLS alone doesn't stop selecting/writing a column).
create policy driver_applications_update on public.driver_applications
  for update using (
    organization_id = public.current_org_id()
    and public.has_role(array['owner', 'admin', 'dispatcher']::public.org_role[])
  )
  with check (organization_id = public.current_org_id());

-- No insert policy at all: rows are created exclusively by
-- submit_driver_application() below, which runs as SECURITY DEFINER and so
-- bypasses RLS regardless of whether the caller is anon or authenticated.

revoke select on public.driver_applications from authenticated, anon;
grant select (
  id, organization_id, status, position_applied_for, availability,
  first_name, middle_name, last_name, date_of_birth, ssn_last4, phone, email,
  address_line1, city, state, postal_code,
  cdl_number, cdl_state, cdl_class, cdl_endorsements, cdl_expiry_date,
  years_of_experience, equipment_experience, employment_history,
  has_been_convicted_of_dui, has_had_license_suspended, has_had_preventable_accident,
  driving_record_explanation, has_valid_medical_card, medical_card_expiry_date,
  uploaded_documents, emergency_contact_name, emergency_contact_phone,
  signature_name, signature_agreed_at, submitted_from_ip,
  reviewed_by, reviewed_at, review_notes, converted_driver_id,
  submitted_at, updated_at
) on public.driver_applications to authenticated;

revoke update on public.driver_applications from authenticated, anon;
grant update (status, reviewed_by, reviewed_at, review_notes) on public.driver_applications to authenticated;

-- ---------------------------------------------------------------------------
-- driver_application_pii_access_log: mirrors driver_pii_access_log (0014) --
-- kept as its own table rather than widening that one, since it references
-- driver_applications, not drivers, and the two shouldn't be joined loosely.
-- ---------------------------------------------------------------------------
create table public.driver_application_pii_access_log (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  application_id uuid not null references public.driver_applications (id) on delete cascade,
  accessed_by uuid not null references public.profiles (id) on delete set null,
  reason text,
  accessed_at timestamptz not null default now()
);

alter table public.driver_application_pii_access_log enable row level security;

create policy driver_application_pii_access_log_select on public.driver_application_pii_access_log
  for select using (
    organization_id = public.current_org_id()
    and public.has_role(array['owner', 'admin']::public.org_role[])
  );

comment on table public.driver_application_pii_access_log is
  'Immutable audit trail of every applicant SSN reveal. Written exclusively by reveal_driver_application_pii(); no update/delete policy exists.';

-- ---------------------------------------------------------------------------
-- Private storage bucket for uploaded application documents (CDL copy,
-- medical card, resume, ...). No storage.objects policies are added for
-- anon or authenticated -- every read and write goes through a route
-- handler / server action using the service_role key, which bypasses
-- storage RLS entirely after independently verifying who's asking.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'driver-application-documents',
  'driver-application-documents',
  false,
  10485760, -- 10 MB
  array['application/pdf', 'image/jpeg', 'image/png', 'image/heic']
)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- submit_driver_application: the one and only way a row can be created.
-- Grantable to anon since the applicant has no Supabase Auth session at all.
-- p_id lets the caller (the /api/driver-application/submit route handler)
-- pre-generate the application id client-side-adjacent so document uploads
-- (which happen as the applicant attaches files, before final submit) can
-- be written to storage under that id ahead of this call.
-- ---------------------------------------------------------------------------
create or replace function public.submit_driver_application(
  p_id uuid,
  p_organization_id uuid,
  p_position_applied_for text,
  p_availability text,
  p_first_name text,
  p_middle_name text,
  p_last_name text,
  p_date_of_birth date,
  p_ssn text,
  p_phone text,
  p_email text,
  p_address_line1 text,
  p_city text,
  p_state text,
  p_postal_code text,
  p_cdl_number text,
  p_cdl_state text,
  p_cdl_class text,
  p_cdl_endorsements text,
  p_cdl_expiry_date date,
  p_years_of_experience numeric,
  p_equipment_experience text,
  p_employment_history jsonb,
  p_has_been_convicted_of_dui boolean,
  p_has_had_license_suspended boolean,
  p_has_had_preventable_accident boolean,
  p_driving_record_explanation text,
  p_has_valid_medical_card boolean,
  p_medical_card_expiry_date date,
  p_uploaded_documents jsonb,
  p_emergency_contact_name text,
  p_emergency_contact_phone text,
  p_signature_name text,
  p_submitted_from_ip text
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_key text;
  v_ssn_encrypted bytea;
  v_ssn_last4 text;
begin
  if p_first_name is null or trim(p_first_name) = '' or p_last_name is null or trim(p_last_name) = '' then
    raise exception 'First and last name are required';
  end if;
  if p_signature_name is null or trim(p_signature_name) = '' then
    raise exception 'Electronic signature (typed full legal name) is required';
  end if;
  if not exists (select 1 from public.organizations where id = p_organization_id) then
    raise exception 'Unknown organization';
  end if;

  if p_ssn is not null and trim(p_ssn) <> '' then
    if p_ssn !~ '^\d{3}-\d{2}-\d{4}$' then
      raise exception 'SSN must be in the format XXX-XX-XXXX';
    end if;
    v_key := public.get_app_encryption_key('driver_pii_key');
    v_ssn_encrypted := pgp_sym_encrypt(p_ssn, v_key);
    v_ssn_last4 := right(p_ssn, 4);
  end if;

  insert into public.driver_applications (
    id, organization_id, position_applied_for, availability,
    first_name, middle_name, last_name, date_of_birth, ssn_encrypted, ssn_last4,
    phone, email, address_line1, city, state, postal_code,
    cdl_number, cdl_state, cdl_class, cdl_endorsements, cdl_expiry_date,
    years_of_experience, equipment_experience, employment_history,
    has_been_convicted_of_dui, has_had_license_suspended, has_had_preventable_accident,
    driving_record_explanation, has_valid_medical_card, medical_card_expiry_date,
    uploaded_documents, emergency_contact_name, emergency_contact_phone,
    signature_name, submitted_from_ip
  ) values (
    p_id, p_organization_id, p_position_applied_for, p_availability,
    p_first_name, p_middle_name, p_last_name, p_date_of_birth, v_ssn_encrypted, v_ssn_last4,
    p_phone, p_email, p_address_line1, p_city, p_state, p_postal_code,
    p_cdl_number, p_cdl_state, p_cdl_class, p_cdl_endorsements, p_cdl_expiry_date,
    p_years_of_experience, p_equipment_experience, coalesce(p_employment_history, '[]'::jsonb),
    p_has_been_convicted_of_dui, p_has_had_license_suspended, p_has_had_preventable_accident,
    p_driving_record_explanation, p_has_valid_medical_card, p_medical_card_expiry_date,
    coalesce(p_uploaded_documents, '[]'::jsonb), p_emergency_contact_name, p_emergency_contact_phone,
    p_signature_name, p_submitted_from_ip
  );

  return p_id;
end;
$$;

grant execute on function public.submit_driver_application(
  uuid, uuid, text, text, text, text, text, date, text, text, text, text, text, text, text,
  text, text, text, text, date, numeric, text, jsonb, boolean, boolean, boolean, text,
  boolean, date, jsonb, text, text, text, text
) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- reveal_driver_application_pii: owner/admin-only, logged every time.
-- ---------------------------------------------------------------------------
create or replace function public.reveal_driver_application_pii(p_application_id uuid, p_reason text default null)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_org_id uuid;
  v_key text;
  v_encrypted bytea;
begin
  select organization_id, ssn_encrypted into v_org_id, v_encrypted
  from public.driver_applications where id = p_application_id;

  if v_org_id is null or v_org_id <> public.current_org_id() then
    raise exception 'Application not found in your organization';
  end if;
  if not public.has_role(array['owner', 'admin']::public.org_role[]) then
    raise exception 'Only owners and admins may reveal this field';
  end if;
  if v_encrypted is null then
    return null;
  end if;

  v_key := public.get_app_encryption_key('driver_pii_key');

  insert into public.driver_application_pii_access_log (organization_id, application_id, accessed_by, reason)
  values (v_org_id, p_application_id, auth.uid(), p_reason);

  return pgp_sym_decrypt(v_encrypted, v_key);
end;
$$;

grant execute on function public.reveal_driver_application_pii(uuid, text) to authenticated;

-- ---------------------------------------------------------------------------
-- convert_driver_application_to_driver: creates a real drivers row from an
-- approved application. The encrypted SSN ciphertext is copied byte-for-byte
-- from the application to the new driver row -- it is never decrypted in
-- this function, so the plaintext SSN does not exist anywhere in memory
-- during conversion, only at the two points it always has: the applicant's
-- original submission, and a logged owner/admin reveal.
-- ---------------------------------------------------------------------------
create or replace function public.convert_driver_application_to_driver(p_application_id uuid, p_carrier_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_app public.driver_applications;
  v_driver_id uuid;
begin
  select * into v_app from public.driver_applications where id = p_application_id;
  if v_app.id is null or v_app.organization_id <> public.current_org_id() then
    raise exception 'Application not found in your organization';
  end if;
  if not public.has_role(array['owner', 'admin']::public.org_role[]) then
    raise exception 'Only owners and admins may convert an application';
  end if;
  if v_app.status = 'converted' then
    raise exception 'This application has already been converted';
  end if;
  if not exists (select 1 from public.carriers where id = p_carrier_id and organization_id = v_app.organization_id) then
    raise exception 'Carrier not found in your organization';
  end if;

  insert into public.drivers (
    organization_id, carrier_id, first_name, middle_name, last_name, phone, email,
    date_of_birth, address_line1, city, state, postal_code,
    emergency_contact_name, emergency_contact_phone,
    cdl_number, cdl_state, cdl_class, cdl_endorsements, cdl_expiry_date,
    medical_card_expiry_date, status, ssn_encrypted, ssn_last4
  ) values (
    v_app.organization_id, p_carrier_id, v_app.first_name, v_app.middle_name, v_app.last_name,
    v_app.phone, v_app.email, v_app.date_of_birth, v_app.address_line1, v_app.city, v_app.state, v_app.postal_code,
    v_app.emergency_contact_name, v_app.emergency_contact_phone,
    v_app.cdl_number, v_app.cdl_state, v_app.cdl_class, v_app.cdl_endorsements, v_app.cdl_expiry_date,
    v_app.medical_card_expiry_date, 'applicant', v_app.ssn_encrypted, v_app.ssn_last4
  )
  returning id into v_driver_id;

  update public.driver_applications
    set status = 'converted', converted_driver_id = v_driver_id, updated_at = now()
    where id = p_application_id;

  return v_driver_id;
end;
$$;

grant execute on function public.convert_driver_application_to_driver(uuid, uuid) to authenticated;
