#!/usr/bin/env bash
# Regenerates supabase/DRIFT_CHECK_READONLY.sql from the production twin.
# Run after adding a migration; then run the generated file (read-only) in the
# Supabase SQL Editor -- no rows means production matches the repository.
# Usage: PGPORT=55900 bash supabase/ci/make-drift-check.sh
set -eu
cd "$(dirname "$0")/.."
OUT="$(mktemp -d)"
{
  printf '\\o %s/groups.txt\n\\pset format unaligned\n\\pset tuples_only on\n\\pset fieldsep |\n' "$OUT"
  printf "select kind, grp, left(md5(string_agg(name || '=' || md5(fp), ';' order by name)), 12), count(*) from (\n"
  grep -v '^--' ci/drift_catalog_rows.sql
  printf ") x group by 1, 2 order by 1, 2;\n"
} > "$OUT/dump.sql"
bash ci/twin-db.sh "$OUT/dump.sql" >/dev/null
python3 - "$OUT/groups.txt" ci/drift_catalog_rows.sql DRIFT_CHECK_READONLY.sql <<'PY'
import sys
groups, rows_sql, out = sys.argv[1:]
live = "".join(l for l in open(rows_sql) if not l.startswith("--"))
q = lambda s: "'" + s.replace("'", "''") + "'"
rows = [l.rstrip("\n").split("|") for l in open(groups) if l.strip()]
vals = ",\n".join(f"({q(k)},{q(g)},{q(h)},{n})" for k, g, h, n in rows)
open(out, "w").write(f"""-- DRIFT_CHECK_READONLY.sql -- READ-ONLY. GENERATED by supabase/ci/make-drift-check.sh; do not edit.
-- Compares the live schema with the schema the repository's migrations build.
-- No rows = production matches the repository. (rls_auto_enable() is created
-- by Supabase itself and is expected to show as ONLY IN PRODUCTION.)
with expected(kind, grp, fp, n) as (values
{vals}
),
live_rows as ({live}),
live as (
  select kind, grp, left(md5(string_agg(name || '=' || md5(fp), ';' order by name)), 12) as fp, count(*) as n
  from live_rows group by 1, 2
)
select coalesce(l.kind, e.kind) as kind, coalesce(l.grp, e.grp) as object,
       case when e.kind is null then 'ONLY IN PRODUCTION' when l.kind is null then 'MISSING IN PRODUCTION' else 'DIFFERENT' end as status,
       coalesce(l.n::text, '-') || ' live / ' || coalesce(e.n::text, '-') || ' repo' as items
from live l full join expected e on e.kind = l.kind and e.grp = l.grp
where e.fp is distinct from l.fp
order by 3, 1, 2;
""")
print(f"wrote {out}: {len(rows)} schema groups")
PY
rm -rf "$OUT"
