import Link from "next/link";
import { StatusBadge } from "@/components/ui/status-badge";

export type PackageHistoryRow = {
  id: string;
  version: number;
  status: string;
  prepared_for_name: string | null;
  recipient_name: string | null;
  document_count: number;
  generated_at: string | null;
  last_sent_at: string | null;
  generated_by_profile: { full_name: string } | null;
};

export function PackageHistory({ applicationId, rows, canGenerate }: { applicationId: string; rows: PackageHistoryRow[]; canGenerate: boolean }) {
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-[14px] font-semibold text-desktop-text">Setup Packages</h2>
          <p className="text-[12.5px] text-muted-foreground">Immutable broker-ready packages generated from verified current documents.</p>
        </div>
        {canGenerate && <Link href={`/carriers/onboarding/${applicationId}/setup-packages/new`} className="inline-flex h-8 items-center rounded-sm bg-primary px-3 text-[13px] font-medium text-primary-foreground">Generate Setup Package</Link>}
      </div>
      {rows.length === 0 ? (
        <div className="rounded-md border border-dashed border-desktop-border p-6 text-center text-[13px] text-muted-foreground">No setup packages have been generated.</div>
      ) : (
        <>
          <div className="hidden overflow-hidden rounded-md border border-desktop-border md:block">
            <table className="w-full text-left text-[12.5px]">
              <thead className="bg-desktop-muted text-muted-foreground"><tr>{["Version","Generated","Prepared For","Documents","Status","Last Sent","Generated By",""].map((h) => <th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead>
              <tbody className="divide-y divide-desktop-border">{rows.map((row) => <tr key={row.id} className="bg-card">
                <td className="px-3 py-2 font-medium">v{row.version}</td><td className="px-3 py-2">{date(row.generated_at)}</td><td className="px-3 py-2">{row.prepared_for_name || row.recipient_name || "Generic"}</td><td className="px-3 py-2">{row.document_count}</td><td className="px-3 py-2"><StatusBadge status={row.status} /></td><td className="px-3 py-2">{date(row.last_sent_at)}</td><td className="px-3 py-2">{row.generated_by_profile?.full_name ?? "-"}</td><td className="px-3 py-2 text-right"><Link className="font-medium text-primary hover:underline" href={`/carriers/onboarding/${applicationId}/setup-packages/${row.id}`}>View</Link></td>
              </tr>)}</tbody>
            </table>
          </div>
          <div className="space-y-2 md:hidden">{rows.map((row) => <Link key={row.id} href={`/carriers/onboarding/${applicationId}/setup-packages/${row.id}`} className="block rounded-md border border-desktop-border bg-card p-3">
            <div className="flex items-center justify-between"><span className="font-medium">Package v{row.version}</span><StatusBadge status={row.status} /></div>
            <dl className="mt-2 grid grid-cols-2 gap-2 text-[12px]"><div><dt className="text-muted-foreground">Generated</dt><dd>{date(row.generated_at)}</dd></div><div><dt className="text-muted-foreground">Documents</dt><dd>{row.document_count}</dd></div><div><dt className="text-muted-foreground">Prepared For</dt><dd>{row.prepared_for_name || row.recipient_name || "Generic"}</dd></div><div><dt className="text-muted-foreground">Last Sent</dt><dd>{date(row.last_sent_at)}</dd></div></dl>
          </Link>)}</div>
        </>
      )}
    </div>
  );
}
function date(value: string | null) { return value ? new Date(value).toLocaleString() : "-"; }
