-- GENERATED by role_fixture/build_fixture.py. SYNTHETIC ONLY; NOT APPROVED FOR PRODUCTION.
begin;
do $guard$ declare m record; begin
  if current_user<>session_user then raise exception 'F30_OPERATOR_REQUIRED'; end if;
  if to_regclass('f30_test_control.marker') is null then raise exception using errcode='P0001', message='F30_TEST_MARKER_REQUIRED'; end if;
  select * into strict m from f30_test_control.marker;
  if m.environment is distinct from 'nonproduction-f30' or m.database_name is distinct from current_database()
     or m.project_ref is null
     or m.project_ref in ('zteixenjpcygjvznueuo','fjmrvvyjvqdyopnyetez')
     or m.project_ref like 'fjmrvvyjvqd%' or m.project_ref !~ '^[a-z0-9]{20}$'
     or m.fixture_id is distinct from 'F30_SYNTHETIC_ROLE_MODEL_V1'
     or (m.project_ref = 'localdisposablef30xx' and (inet_server_addr() is not null or current_database() <> 'frz_lab')) then
    raise exception using errcode='P0001', message='F30_TEST_TARGET_REFUSED';
  end if;
  if exists(select 1 from pg_class c where c.oid='f30_test_control.marker'::regclass and c.relowner <> (select oid from pg_roles where rolname=current_user))
     or exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a
               where c.oid='f30_test_control.marker'::regclass and a.grantee<>c.relowner) then
    raise exception using errcode='P0001', message='F30_MARKER_OWNERSHIP_OR_ACL_DRIFT';
  end if;

  if current_setting('f30.expected_project_ref',true) is distinct from m.project_ref then raise exception 'F30_EXPLICIT_TARGET_REQUIRED'; end if;
  if to_regclass('ops_freeze_v2.freeze_run') is not null then
    if exists(select 1 from ops_freeze_v2.freeze_run where status='frozen') then raise exception 'F30_ACTIVE_FREEZE_REFUSED'; end if;
  end if;
  if exists(select 1 from pg_trigger where tgname='0_ops_freeze_block_writes' and not tgisinternal) then raise exception 'F30_ORPHAN_FREEZE_TRIGGER_REFUSED'; end if;
  perform pg_advisory_xact_lock(303030157);
end $guard$;
do $install$ declare actual text; begin
  if to_regnamespace('f30_probe') is not null then
    if (select source_hash from f30_probe.manifest where singleton) is distinct from 'dee0591ed7b99629d773bebf3682d98010ef75652af14636b58477f645cf260c' then raise exception 'F30_SOURCE_DRIFT'; end if;
    execute 'select md5(
  coalesce((select string_agg(concat_ws(''|'',c.relname,c.relkind,c.relowner::regrole::text,c.relacl::text,c.relrowsecurity::text),'';'' order by c.relname) from pg_class c where c.relnamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',c.relname,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull::text,a.attacl::text),'';'' order by c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid where c.relnamespace=''f30_probe''::regnamespace and a.attnum>0 and not a.attisdropped),'''') ||
  coalesce((select string_agg(concat_ws(''|'',conname,pg_get_constraintdef(oid)), '';'' order by conname) from pg_constraint where connamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'',pg_get_functiondef(p.oid),p.proowner::regrole::text,p.proacl::text),'';'' order by p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'') from pg_proc p where p.pronamespace=''f30_probe''::regnamespace or (p.pronamespace=''public''::regnamespace and p.proname in (''f30_probe_action'',''f30_probe_context''))),'''') ||
  coalesce((select string_agg(pg_get_triggerdef(t.oid),'';'' order by t.tgname,c.relname) from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace=''f30_probe''::regnamespace and not t.tgisinternal and t.tgname<>''0_ops_freeze_block_writes''),'''') ||
  coalesce((select string_agg(concat_ws(''|'',polname,polcmd,polroles::text,pg_get_expr(polqual,polrelid),pg_get_expr(polwithcheck,polrelid)),'';'' order by polname) from pg_policy where polrelid in(select oid from pg_class where relnamespace=''f30_probe''::regnamespace)),'''') ||
  (select concat_ws(''|'',nspowner::regrole::text,nspacl::text,obj_description(oid,''pg_namespace'')) from pg_namespace where nspname=''f30_probe''))' into actual;
    if actual is distinct from (select catalog_hash from f30_probe.manifest where singleton) then raise exception 'F30_CATALOG_DRIFT'; end if;
    execute 'select md5(coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.organizations t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.memberships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carriers t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.parties t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.factors t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.relationships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.loads t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.dispatches t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.invoices t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carrier_grants t),''''))' into actual;
    if actual is distinct from (select seed_hash from f30_probe.manifest where singleton) then raise exception 'F30_SEED_DRIFT'; end if;

    if exists(select 1 from f30_probe.receipts) then raise exception 'F30_RECEIPTS_REQUIRE_RESET'; end if;
    return;
  end if;
  if exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in ('f30_probe_action','f30_probe_context')) then raise exception 'F30_RPC_COLLISION'; end if;
  execute '-- Synthetic authorization model ONLY. No application migrations, issuance or factoring enabled.
create schema f30_probe;
comment on schema f30_probe is ''F30_SYNTHETIC_ROLE_MODEL_V1'';
revoke all on schema f30_probe from public, anon, authenticated, service_role;
create table f30_probe.organizations (id uuid primary key, label text not null unique);
create table f30_probe.memberships (
  id uuid primary key, organization_id uuid not null references f30_probe.organizations,
  role text not null check (role in (''owner'',''admin'',''dispatcher'',''accountant'',''driver'',''viewer'')),
  label text not null, unique (organization_id,id)
);
create table f30_probe.carriers (id uuid primary key, organization_id uuid not null references f30_probe.organizations, unique(organization_id,id));
create table f30_probe.parties (id uuid primary key, organization_id uuid not null references f30_probe.organizations, kind text not null check(kind in (''broker'',''customer'')), unique(organization_id,id));
create table f30_probe.factors (id uuid primary key, organization_id uuid not null references f30_probe.organizations, unique(organization_id,id));
create table f30_probe.relationships (
  id uuid primary key, organization_id uuid not null, carrier_id uuid not null, factor_id uuid not null,
  routing text not null, terms jsonb not null, unique(organization_id,carrier_id,id),
  foreign key(organization_id,factor_id) references f30_probe.factors(organization_id,id),
  foreign key(organization_id,carrier_id) references f30_probe.carriers(organization_id,id)
);
create table f30_probe.loads (
  id uuid primary key, organization_id uuid not null, carrier_id uuid not null, recipient_id uuid not null,
  freight_amount numeric(12,2) not null check(freight_amount>0), unique(organization_id,carrier_id,id),
  foreign key(organization_id,carrier_id) references f30_probe.carriers(organization_id,id),
  foreign key(organization_id,recipient_id) references f30_probe.parties(organization_id,id)
);
create table f30_probe.dispatches (
  id uuid primary key, organization_id uuid not null, carrier_id uuid not null, load_id uuid not null,
  foreign key(organization_id,carrier_id,load_id) references f30_probe.loads(organization_id,carrier_id,id)
);
create table f30_probe.invoices (
  id uuid primary key, organization_id uuid not null, carrier_id uuid not null, load_id uuid not null, relationship_id uuid not null,
  issuance_status text not null check(issuance_status in (''draft'',''ready_for_issue'',''issued'')),
  unique(organization_id,id),
  foreign key(organization_id,carrier_id,load_id) references f30_probe.loads(organization_id,carrier_id,id),
  foreign key(organization_id,carrier_id,relationship_id) references f30_probe.relationships(organization_id,carrier_id,id)
);
create table f30_probe.carrier_grants (
  organization_id uuid not null, carrier_id uuid not null, profile_id uuid not null,
  primary key(organization_id,carrier_id,profile_id),
  foreign key(organization_id,carrier_id) references f30_probe.carriers(organization_id,id),
  foreign key(organization_id,profile_id) references f30_probe.memberships(organization_id,id)
);
-- Intent receipts exercise the freeze without issuing an invoice or enabling factoring.
create table f30_probe.receipts (
  organization_id uuid not null, request_key text not null, invoice_id uuid not null, actor_id uuid not null,
  action text not null, resolved jsonb not null,
  primary key(organization_id,request_key),
  foreign key(organization_id,invoice_id) references f30_probe.invoices(organization_id,id),
  foreign key(organization_id,actor_id) references f30_probe.memberships(organization_id,id)
);
create table f30_probe.manifest (singleton boolean primary key check(singleton), source_hash text not null, seed_hash text not null, catalog_hash text not null);

create function f30_probe.check_target() returns void language plpgsql stable security definer set search_path=pg_catalog,pg_temp as $fn$
declare m record;
begin
  if to_regclass(''f30_test_control.marker'') is null then raise exception using errcode=''P0001'', message=''F30_TEST_MARKER_REQUIRED''; end if;
  select * into strict m from f30_test_control.marker;
  if m.environment is distinct from ''nonproduction-f30'' or m.database_name is distinct from current_database()
     or m.project_ref is null
     or m.project_ref in (''zteixenjpcygjvznueuo'',''fjmrvvyjvqdyopnyetez'')
     or m.project_ref like ''fjmrvvyjvqd%'' or m.project_ref !~ ''^[a-z0-9]{20}$''
     or m.fixture_id is distinct from ''F30_SYNTHETIC_ROLE_MODEL_V1''
     or (m.project_ref = ''localdisposablef30xx'' and (inet_server_addr() is not null or current_database() <> ''frz_lab'')) then
    raise exception using errcode=''P0001'', message=''F30_TEST_TARGET_REFUSED'';
  end if;
  if exists(select 1 from pg_class c where c.oid=''f30_test_control.marker''::regclass and c.relowner <> (select oid from pg_roles where rolname=current_user))
     or exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault(''r'',c.relowner))) a
               where c.oid=''f30_test_control.marker''::regclass and a.grantee<>c.relowner) then
    raise exception using errcode=''P0001'', message=''F30_MARKER_OWNERSHIP_OR_ACL_DRIFT'';
  end if;
end $fn$;

create function public.f30_probe_action(p_invoice_id uuid, p_action text, p_request_key text default null)
returns jsonb language plpgsql security definer set search_path=pg_catalog,pg_temp as $fn$
declare u uuid:=auth.uid(); m record; i record; old record; context jsonb;
begin
  perform f30_probe.check_target();
  if u is null then return jsonb_build_object(''code'',''FORBIDDEN''); end if;
  select * into m from f30_probe.memberships where id=u;
  if m.id is null then return jsonb_build_object(''code'',''FORBIDDEN''); end if;
  select * into i from f30_probe.invoices where id=p_invoice_id and organization_id=m.organization_id;
  if i.id is null then return jsonb_build_object(''code'',''NOT_FOUND''); end if;
  if p_action is null or p_action not in (''preview'',''prepare'',''ready'',''discard'',''issue'',''reissue'',''submit'') then
    return jsonb_build_object(''code'',''INVALID_REQUEST'');
  end if;
  if m.role not in (''owner'',''admin'') and not (
    m.role=''dispatcher'' and p_action in (''preview'',''prepare'',''ready'',''discard'') and
    exists(select 1 from f30_probe.carrier_grants g where g.organization_id=m.organization_id and g.carrier_id=i.carrier_id and g.profile_id=u)
  ) then return jsonb_build_object(''code'',''FORBIDDEN''); end if;
  -- Authorization and tenant lookup MUST precede idempotency, including factoring replay.
  if p_action=''preview'' then return jsonb_build_object(''code'',''OK'',''synthetic'',true); end if;
  if p_request_key is null or p_request_key !~ ''^[a-zA-Z0-9_-]{8,80}$'' then return jsonb_build_object(''code'',''INVALID_REQUEST''); end if;
  perform pg_advisory_xact_lock(hashtextextended(m.organization_id::text||'':''||p_request_key,0));
  select * into old from f30_probe.receipts where organization_id=m.organization_id and request_key=p_request_key;
  if old.invoice_id is not null then
    if old.invoice_id<>i.id or old.action<>p_action then return jsonb_build_object(''code'',''IDEMPOTENCY_KEY_REUSED''); end if;
    return jsonb_build_object(''code'',''OK'',''synthetic'',true,''replay'',true);
  end if;
  select jsonb_build_object(''organization'',i.organization_id,''carrier'',i.carrier_id,''relationship'',r.id,''factor'',r.factor_id,
    ''routing'',r.routing,''terms'',r.terms,''recipient'',l.recipient_id,''amount'',l.freight_amount)
    into strict context from f30_probe.loads l join f30_probe.relationships r on r.id=i.relationship_id and r.organization_id=i.organization_id
    where l.id=i.load_id and l.organization_id=i.organization_id;
  insert into f30_probe.receipts values(m.organization_id,p_request_key,i.id,u,p_action,context);
  return jsonb_build_object(''code'',''OK'',''synthetic'',true,''replay'',false);
end $fn$;

create function public.f30_probe_context() returns jsonb language plpgsql stable security definer set search_path=pg_catalog,pg_temp as $fn$
begin
  perform f30_probe.check_target();
  if not exists(select 1 from f30_probe.memberships where id=auth.uid() and role in (''owner'',''admin'')) then
    return jsonb_build_object(''code'',''FORBIDDEN'');
  end if;
  return (select jsonb_build_object(''code'',''OK'',''project_ref'',m.project_ref,''environment'',m.environment,
    ''fixture_id'',m.fixture_id,''source_hash'',f.source_hash,''postgres_version'',current_setting(''server_version''),
    ''seed_matches'',f.seed_hash=(select md5(coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.organizations t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.memberships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carriers t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.parties t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.factors t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.relationships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.loads t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.dispatches t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.invoices t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carrier_grants t),''''))),''catalog_matches'',f.catalog_hash=(select md5(
  coalesce((select string_agg(concat_ws(''|'',c.relname,c.relkind,c.relowner::regrole::text,c.relacl::text,c.relrowsecurity::text),'';'' order by c.relname) from pg_class c where c.relnamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',c.relname,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull::text,a.attacl::text),'';'' order by c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid where c.relnamespace=''f30_probe''::regnamespace and a.attnum>0 and not a.attisdropped),'''') ||
  coalesce((select string_agg(concat_ws(''|'',conname,pg_get_constraintdef(oid)), '';'' order by conname) from pg_constraint where connamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'',pg_get_functiondef(p.oid),p.proowner::regrole::text,p.proacl::text),'';'' order by p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'') from pg_proc p where p.pronamespace=''f30_probe''::regnamespace or (p.pronamespace=''public''::regnamespace and p.proname in (''f30_probe_action'',''f30_probe_context''))),'''') ||
  coalesce((select string_agg(pg_get_triggerdef(t.oid),'';'' order by t.tgname,c.relname) from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace=''f30_probe''::regnamespace and not t.tgisinternal and t.tgname<>''0_ops_freeze_block_writes''),'''') ||
  coalesce((select string_agg(concat_ws(''|'',polname,polcmd,polroles::text,pg_get_expr(polqual,polrelid),pg_get_expr(polwithcheck,polrelid)),'';'' order by polname) from pg_policy where polrelid in(select oid from pg_class where relnamespace=''f30_probe''::regnamespace)),'''') ||
  (select concat_ws(''|'',nspowner::regrole::text,nspacl::text,obj_description(oid,''pg_namespace'')) from pg_namespace where nspname=''f30_probe''))))
    from f30_test_control.marker m cross join f30_probe.manifest f);
end $fn$;
revoke all on function public.f30_probe_action(uuid,text,text),public.f30_probe_context() from public,anon,authenticated,service_role;
grant execute on function public.f30_probe_action(uuid,text,text),public.f30_probe_context() to authenticated;
revoke all on all functions in schema f30_probe from public,anon,authenticated,service_role;
revoke all on all tables in schema f30_probe from public,anon,authenticated,service_role;
';
  execute 'insert into f30_probe.organizations values (''f3000000-0000-0000-0000-000000001000'',''F30 synthetic organization 1'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001001'',''f3000000-0000-0000-0000-000000001000'',''owner'',''org1_owner'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001002'',''f3000000-0000-0000-0000-000000001000'',''admin'',''org1_admin'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001003'',''f3000000-0000-0000-0000-000000001000'',''dispatcher'',''org1_granted_dispatcher'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001004'',''f3000000-0000-0000-0000-000000001000'',''dispatcher'',''org1_ungranted_dispatcher'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001005'',''f3000000-0000-0000-0000-000000001000'',''accountant'',''org1_accountant'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001006'',''f3000000-0000-0000-0000-000000001000'',''driver'',''org1_driver'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000001007'',''f3000000-0000-0000-0000-000000001000'',''viewer'',''org1_viewer'');
insert into f30_probe.carriers values (''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001000'');
insert into f30_probe.parties values (''f3000000-0000-0000-0000-000000001011'',''f3000000-0000-0000-0000-000000001000'',''broker'');
insert into f30_probe.parties values (''f3000000-0000-0000-0000-000000001012'',''f3000000-0000-0000-0000-000000001000'',''customer'');
insert into f30_probe.factors values (''f3000000-0000-0000-0000-000000001014'',''f3000000-0000-0000-0000-000000001000'');
insert into f30_probe.relationships values (''f3000000-0000-0000-0000-000000001013'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001014'',''SYNTHETIC ONLY org 1'',''{"advance":80,"fee":3,"reserve":20,"currency":"USD"}'');
insert into f30_probe.loads values (''f3000000-0000-0000-0000-000000001020'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001011'',1100);
insert into f30_probe.dispatches values (''f3000000-0000-0000-0000-000000001030'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001020'');
insert into f30_probe.invoices values (''f3000000-0000-0000-0000-000000001040'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001020'',''f3000000-0000-0000-0000-000000001013'',''draft'');
insert into f30_probe.loads values (''f3000000-0000-0000-0000-000000001021'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001012'',1110);
insert into f30_probe.dispatches values (''f3000000-0000-0000-0000-000000001031'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001021'');
insert into f30_probe.invoices values (''f3000000-0000-0000-0000-000000001041'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001021'',''f3000000-0000-0000-0000-000000001013'',''ready_for_issue'');
insert into f30_probe.loads values (''f3000000-0000-0000-0000-000000001022'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001011'',1120);
insert into f30_probe.dispatches values (''f3000000-0000-0000-0000-000000001032'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001022'');
insert into f30_probe.invoices values (''f3000000-0000-0000-0000-000000001042'',''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001022'',''f3000000-0000-0000-0000-000000001013'',''issued'');
insert into f30_probe.carrier_grants values (''f3000000-0000-0000-0000-000000001000'',''f3000000-0000-0000-0000-000000001010'',''f3000000-0000-0000-0000-000000001003'');
insert into f30_probe.organizations values (''f3000000-0000-0000-0000-000000002000'',''F30 synthetic organization 2'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002001'',''f3000000-0000-0000-0000-000000002000'',''owner'',''org2_owner'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002002'',''f3000000-0000-0000-0000-000000002000'',''admin'',''org2_admin'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002003'',''f3000000-0000-0000-0000-000000002000'',''dispatcher'',''org2_granted_dispatcher'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002004'',''f3000000-0000-0000-0000-000000002000'',''dispatcher'',''org2_ungranted_dispatcher'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002005'',''f3000000-0000-0000-0000-000000002000'',''accountant'',''org2_accountant'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002006'',''f3000000-0000-0000-0000-000000002000'',''driver'',''org2_driver'');
insert into f30_probe.memberships values (''f3000000-0000-0000-0000-000000002007'',''f3000000-0000-0000-0000-000000002000'',''viewer'',''org2_viewer'');
insert into f30_probe.carriers values (''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002000'');
insert into f30_probe.parties values (''f3000000-0000-0000-0000-000000002011'',''f3000000-0000-0000-0000-000000002000'',''broker'');
insert into f30_probe.parties values (''f3000000-0000-0000-0000-000000002012'',''f3000000-0000-0000-0000-000000002000'',''customer'');
insert into f30_probe.factors values (''f3000000-0000-0000-0000-000000002014'',''f3000000-0000-0000-0000-000000002000'');
insert into f30_probe.relationships values (''f3000000-0000-0000-0000-000000002013'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002014'',''SYNTHETIC ONLY org 2'',''{"advance":80,"fee":3,"reserve":20,"currency":"USD"}'');
insert into f30_probe.loads values (''f3000000-0000-0000-0000-000000002020'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002011'',1200);
insert into f30_probe.dispatches values (''f3000000-0000-0000-0000-000000002030'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002020'');
insert into f30_probe.invoices values (''f3000000-0000-0000-0000-000000002040'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002020'',''f3000000-0000-0000-0000-000000002013'',''draft'');
insert into f30_probe.loads values (''f3000000-0000-0000-0000-000000002021'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002012'',1210);
insert into f30_probe.dispatches values (''f3000000-0000-0000-0000-000000002031'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002021'');
insert into f30_probe.invoices values (''f3000000-0000-0000-0000-000000002041'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002021'',''f3000000-0000-0000-0000-000000002013'',''ready_for_issue'');
insert into f30_probe.loads values (''f3000000-0000-0000-0000-000000002022'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002011'',1220);
insert into f30_probe.dispatches values (''f3000000-0000-0000-0000-000000002032'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002022'');
insert into f30_probe.invoices values (''f3000000-0000-0000-0000-000000002042'',''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002022'',''f3000000-0000-0000-0000-000000002013'',''issued'');
insert into f30_probe.carrier_grants values (''f3000000-0000-0000-0000-000000002000'',''f3000000-0000-0000-0000-000000002010'',''f3000000-0000-0000-0000-000000002003'');';
  execute 'select md5(coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.organizations t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.memberships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carriers t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.parties t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.factors t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.relationships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.loads t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.dispatches t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.invoices t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carrier_grants t),''''))' into actual;
  insert into f30_probe.manifest values(true,'dee0591ed7b99629d773bebf3682d98010ef75652af14636b58477f645cf260c',actual,'pending');
  execute 'select md5(
  coalesce((select string_agg(concat_ws(''|'',c.relname,c.relkind,c.relowner::regrole::text,c.relacl::text,c.relrowsecurity::text),'';'' order by c.relname) from pg_class c where c.relnamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',c.relname,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull::text,a.attacl::text),'';'' order by c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid where c.relnamespace=''f30_probe''::regnamespace and a.attnum>0 and not a.attisdropped),'''') ||
  coalesce((select string_agg(concat_ws(''|'',conname,pg_get_constraintdef(oid)), '';'' order by conname) from pg_constraint where connamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'',pg_get_functiondef(p.oid),p.proowner::regrole::text,p.proacl::text),'';'' order by p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'') from pg_proc p where p.pronamespace=''f30_probe''::regnamespace or (p.pronamespace=''public''::regnamespace and p.proname in (''f30_probe_action'',''f30_probe_context''))),'''') ||
  coalesce((select string_agg(pg_get_triggerdef(t.oid),'';'' order by t.tgname,c.relname) from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace=''f30_probe''::regnamespace and not t.tgisinternal and t.tgname<>''0_ops_freeze_block_writes''),'''') ||
  coalesce((select string_agg(concat_ws(''|'',polname,polcmd,polroles::text,pg_get_expr(polqual,polrelid),pg_get_expr(polwithcheck,polrelid)),'';'' order by polname) from pg_policy where polrelid in(select oid from pg_class where relnamespace=''f30_probe''::regnamespace)),'''') ||
  (select concat_ws(''|'',nspowner::regrole::text,nspacl::text,obj_description(oid,''pg_namespace'')) from pg_namespace where nspname=''f30_probe''))' into actual;
  update f30_probe.manifest set catalog_hash=actual;
end $install$;
commit;
