-- GENERATED by role_fixture/build_fixture.py. SYNTHETIC ONLY; NOT APPROVED FOR PRODUCTION.
begin;
do $guard$ declare m record; begin
  if current_user<>session_user then raise exception 'F30_OPERATOR_REQUIRED'; end if;
  if to_regclass('f30_test_control.marker') is null then raise exception using errcode='P0001', message='F30_TEST_MARKER_REQUIRED'; end if;
  select * into strict m from f30_test_control.marker;
  if m.environment is distinct from 'nonproduction-f30' or m.database_name is distinct from current_database()
     or m.project_ref is null
     or m.project_ref in ('zteixenjpcygjvznueuo','fjmrvvyjvqdyopnyetez')
     or m.project_ref like 'fjmrvvyjvqd%' or m.project_ref !~ '^[a-z0-9]{20}$'
     or m.fixture_id is distinct from 'F30_SYNTHETIC_ROLE_MODEL_V1'
     or (m.project_ref = 'localdisposablef30xx' and (inet_server_addr() is not null or current_database() <> 'frz_lab')) then
    raise exception using errcode='P0001', message='F30_TEST_TARGET_REFUSED';
  end if;
  if exists(select 1 from pg_class c where c.oid='f30_test_control.marker'::regclass and c.relowner <> (select oid from pg_roles where rolname=current_user))
     or exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a
               where c.oid='f30_test_control.marker'::regclass and a.grantee<>c.relowner) then
    raise exception using errcode='P0001', message='F30_MARKER_OWNERSHIP_OR_ACL_DRIFT';
  end if;

  if current_setting('f30.expected_project_ref',true) is distinct from m.project_ref then raise exception 'F30_EXPLICIT_TARGET_REQUIRED'; end if;
  if to_regclass('ops_freeze_v2.freeze_run') is not null then
    if exists(select 1 from ops_freeze_v2.freeze_run where status='frozen') then raise exception 'F30_ACTIVE_FREEZE_REFUSED'; end if;
  end if;
  if exists(select 1 from pg_trigger where tgname='0_ops_freeze_block_writes' and not tgisinternal) then raise exception 'F30_ORPHAN_FREEZE_TRIGGER_REFUSED'; end if;
  perform pg_advisory_xact_lock(303030157);
end $guard$;
do $reset$ declare actual text; begin
  if (select source_hash from f30_probe.manifest where singleton) is distinct from 'dee0591ed7b99629d773bebf3682d98010ef75652af14636b58477f645cf260c' then raise exception 'F30_SOURCE_DRIFT'; end if;
    execute 'select md5(
  coalesce((select string_agg(concat_ws(''|'',c.relname,c.relkind,c.relowner::regrole::text,c.relacl::text,c.relrowsecurity::text),'';'' order by c.relname) from pg_class c where c.relnamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',c.relname,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull::text,a.attacl::text),'';'' order by c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid where c.relnamespace=''f30_probe''::regnamespace and a.attnum>0 and not a.attisdropped),'''') ||
  coalesce((select string_agg(concat_ws(''|'',conname,pg_get_constraintdef(oid)), '';'' order by conname) from pg_constraint where connamespace=''f30_probe''::regnamespace),'''') ||
  coalesce((select string_agg(concat_ws(''|'',p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'',pg_get_functiondef(p.oid),p.proowner::regrole::text,p.proacl::text),'';'' order by p.pronamespace::regnamespace::text||''.''||p.proname||''(''||pg_get_function_identity_arguments(p.oid)||'')'') from pg_proc p where p.pronamespace=''f30_probe''::regnamespace or (p.pronamespace=''public''::regnamespace and p.proname in (''f30_probe_action'',''f30_probe_context''))),'''') ||
  coalesce((select string_agg(pg_get_triggerdef(t.oid),'';'' order by t.tgname,c.relname) from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace=''f30_probe''::regnamespace and not t.tgisinternal and t.tgname<>''0_ops_freeze_block_writes''),'''') ||
  coalesce((select string_agg(concat_ws(''|'',polname,polcmd,polroles::text,pg_get_expr(polqual,polrelid),pg_get_expr(polwithcheck,polrelid)),'';'' order by polname) from pg_policy where polrelid in(select oid from pg_class where relnamespace=''f30_probe''::regnamespace)),'''') ||
  (select concat_ws(''|'',nspowner::regrole::text,nspacl::text,obj_description(oid,''pg_namespace'')) from pg_namespace where nspname=''f30_probe''))' into actual;
    if actual is distinct from (select catalog_hash from f30_probe.manifest where singleton) then raise exception 'F30_CATALOG_DRIFT'; end if;
    execute 'select md5(coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.organizations t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.memberships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carriers t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.parties t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.factors t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.relationships t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.loads t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.dispatches t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.invoices t),'''') || ''|'' || coalesce((select string_agg(to_jsonb(t)::text,''|'' order by to_jsonb(t)::text) from f30_probe.carrier_grants t),''''))' into actual;
    if actual is distinct from (select seed_hash from f30_probe.manifest where singleton) then raise exception 'F30_SEED_DRIFT'; end if;

  delete from f30_probe.receipts;
  if exists(select 1 from f30_probe.receipts) then raise exception 'F30_RECEIPTS_REQUIRE_RESET'; end if;
end $reset$;
commit;
