-- NOT APPROVED FOR PRODUCTION. Disposable synthetic model only.
\set ON_ERROR_STOP on
BEGIN TRANSACTION READ ONLY;
DO $$ BEGIN
 RAISE EXCEPTION '0148_REFUSED_BACKFILL_DISABLED_NO_SIGNED_PLAN';
END $$;
ROLLBACK;
