-- =============================================================================
-- preflight.sql
-- PROPOSAL 0149 -- NOT APPROVED FOR PRODUCTION. NOT APPLIED. NOT A PRODUCTION MIGRATION.
-- Generated by build.py from supabase/migrations/0129_atomic_dispatch_lifecycle.sql.
--
-- Run BEFORE applying 0149: proves the live functions are exactly the defective 0129 baseline (and re-run AFTER rollback to prove restoration).
-- READ-ONLY: ONE select statement over the system catalogs. It contains no
-- data-changing or schema-changing statement, no transaction control, no
-- temporary object, and no routine other than built-in catalog-inspection
-- functions. It reads the LIVE database (pg_proc, pg_enum, pg_attribute, ...).
-- Expected values embedded below are fingerprints of the 0129 source text.
-- RESULT: on success every row is INFO or PASS and the last row is
-- RESULT | PREFLIGHT | PASS. If any check fails the statement RAISES AN ERROR
-- (invalid input syntax for type integer: "PREFLIGHT FAIL ...") whose text is the
-- complete report -- paste that error text back. Remarks (dash-dash text) and
-- whitespace inside function bodies are ignored (md5 of remark-free, whitespace-free text).
-- =============================================================================
with expect(idx, fname, sig, rettype, args, descr_md5, body_md5, decl, n_use, n_tok) as (values
    (1, 'create_dispatch', 'public.create_dispatch(uuid,uuid,uuid,uuid,uuid,numeric,text)', 'uuid', 'p_load_id uuid, p_carrier_id uuid, p_truck_id uuid, p_driver_id uuid, p_trailer_id uuid default null::uuid, p_dispatch_fee_percentage numeric default null::numeric, p_notes text default null::text', '932fd6c42b6ea8fe00a6f65c91fa12fa', 'f583544e98d49f21f81c1a6998b02e22', 'text[]', 7, 8),
    (2, 'cancel_dispatch', 'public.cancel_dispatch(uuid,text)', 'void', 'p_dispatch_id uuid, p_reason text default null::text', 'a5a3f91bccd955b92c1ca4e121694f38', '0979e90a1ea4f897088871a57bbb65d9', 'text[]', 1, 2)
),
p as (
  select e.idx, e.fname, e.sig, e.rettype as exp_rettype, e.args as exp_args, e.descr_md5 as exp_descr_md5,
         e.body_md5 as exp_body_md5, e.decl as exp_decl, e.n_use, e.n_tok,
         x.oid, x.oid::regprocedure::text as identity, pg_get_function_identity_arguments(x.oid) as identity_args,
         lower(regexp_replace(pg_get_function_arguments(x.oid), '\s+', ' ', 'g')) as args,
         x.prorettype::regtype::text as rettype, l.lanname::text as lang, x.prosecdef,
         x.provolatile::text as vol, x.proparallel::text as par, x.proisstrict, x.proleakproof,
         x.proconfig, x.proacl, x.proowner::regrole::text as owner,
         obj_description(x.oid, 'pg_proc') as descr, length(x.prosrc) as src_len,
         regexp_replace(lower(regexp_replace(x.prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g') as norm
  from expect e
  left join pg_proc x on x.oid = to_regprocedure(e.sig)
  left join pg_language l on l.oid = x.prolang
),
rows as (
  -- server
  select 100 as ord, 'SERVER' as section, 'server_version' as item, 'INFO' as result, current_setting('server_version')::text as detail
  union all select 101, 'SERVER', 'server_version_num', 'INFO', current_setting('server_version_num')::text
  union all select 102, 'SERVER', 'version()', 'INFO', version()::text
  union all
  -- per-function facts read from the LIVE pg_proc row
  select 1000 + 100 * p.idx + v.n, 'FUNCTION', p.fname || ': ' || v.k, 'INFO', v.d
  from p cross join lateral (values
    (1,  'identity',                  coalesce(p.identity, 'MISSING')::text),
    (2,  'identity arguments',        coalesce(p.identity_args, 'MISSING')::text),
    (3,  'arguments with defaults',   coalesce(p.args, 'MISSING')::text),
    (4,  'returns',                   coalesce(p.rettype, 'MISSING')::text),
    (5,  'language',                  coalesce(p.lang, 'MISSING')::text),
    (6,  'volatility',                coalesce(case p.vol when 'v' then 'VOLATILE' when 's' then 'STABLE' when 'i' then 'IMMUTABLE' else p.vol end, 'MISSING')::text),
    (7,  'parallel safety',           coalesce(case p.par when 'u' then 'UNSAFE' when 's' then 'SAFE' when 'r' then 'RESTRICTED' else p.par end, 'MISSING')::text),
    (8,  'security mode',             coalesce(case when p.prosecdef then 'SECURITY DEFINER' else 'SECURITY INVOKER' end, 'MISSING')::text),
    (9,  'strict / leakproof',        coalesce(p.proisstrict::text || ' / ' || p.proleakproof::text, 'MISSING')::text),
    (10, 'configuration (search_path)', coalesce(p.proconfig::text, '(none)')::text),
    (11, 'owner',                     coalesce(p.owner, 'MISSING')::text),
    (12, 'raw ACL',                   coalesce(p.proacl::text, 'NULL (defaults apply: PUBLIC may execute)')::text),
    (13, 'EXECUTE privilege',         coalesce('authenticated=' || has_function_privilege('authenticated', p.oid, 'EXECUTE')::text
                                        || ' anon=' || has_function_privilege('anon', p.oid, 'EXECUTE')::text
                                        || ' service_role=' || has_function_privilege('service_role', p.oid, 'EXECUTE')::text
                                        || ' PUBLIC=' || (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%'))::text, 'MISSING')::text),
    (14, 'declared c_active type',    coalesce(nullif(split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1), ''), '(no c_active declaration)')::text),
    (15, 'live body md5 (normalised)', coalesce(md5(p.norm) || '  (expected ' || p.exp_body_md5 || ')', 'MISSING')::text),
    (16, 'live source length',        coalesce(p.src_len::text || ' chars', 'MISSING')::text)
  ) v(n, k, d)
  union all
  -- dispatches.status and the enum
  select 2000, 'DISPATCHES', 'dispatches.status column type', 'INFO',
         coalesce((select format_type(a.atttypid, a.atttypmod) from pg_attribute a
                    where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), 'MISSING')::text
  union all
  select 2001, 'DISPATCHES', 'dispatch_status enum values (in sort order)', 'INFO',
         coalesce((select string_agg(e.enumlabel::text, ', ' order by e.enumsortorder) from pg_enum e
                    where e.enumtypid = to_regtype('public.dispatch_status')), 'MISSING')::text
  union all
  select 2002, 'BLAST RADIUS', 'public functions declaring c_active constant text[]', 'INFO',
         coalesce((select string_agg(x.proname::text, ', ' order by x.proname) from pg_proc x
                    where x.pronamespace = 'public'::regnamespace
                      and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%'), '(none)')::text
  union all
  -- per-function checks (PASS / FAIL)
  select 3000 + 100 * p.idx + c.n, 'CHECK', p.fname || ': ' || c.title,
         case when coalesce(c.ok, false) then 'PASS' else 'FAIL' end, coalesce(c.d, 'null')::text
  from p cross join lateral (values
    (1,  'exact signature exists in the live database',
         p.oid is not null, coalesce(p.identity, 'MISSING')::text),
    (2,  'single overload by name',
         (select count(*) from pg_proc y where y.pronamespace = 'public'::regnamespace and y.proname = p.fname) = 1,
         (select count(*) from pg_proc y where y.pronamespace = 'public'::regnamespace and y.proname = p.fname)::text),
    (3,  'plpgsql, SECURITY INVOKER, VOLATILE, PARALLEL UNSAFE, not strict, not leakproof, expected return type',
         p.lang = 'plpgsql' and not p.prosecdef and p.vol = 'v' and p.par = 'u' and not p.proisstrict and not p.proleakproof and p.rettype = p.exp_rettype,
         p.lang || ' definer=' || p.prosecdef::text || ' vol=' || p.vol || ' par=' || p.par || ' returns=' || p.rettype),
    (4,  'search_path is exactly public (sole configuration entry)',
         p.proconfig = array['search_path=public']::text[], coalesce(p.proconfig::text, '(none)')),
    (5,  'argument list and defaults unchanged',
         p.args = p.exp_args, coalesce(p.args, 'MISSING')),
    (6,  'EXECUTE granted to authenticated only (not PUBLIC, anon or service_role)',
         p.proacl is not null
           and has_function_privilege('authenticated', p.oid, 'EXECUTE')
           and not has_function_privilege('anon', p.oid, 'EXECUTE')
           and not has_function_privilege('service_role', p.oid, 'EXECUTE')
           and not exists (select 1 from unnest(p.proacl) a where a::text like '=%'),
         coalesce(p.proacl::text, 'NULL')),
    (7,  'function description unchanged from 0129',
         md5(p.descr) = p.exp_descr_md5, coalesce(md5(p.descr), 'MISSING')),
    (8,  'body fingerprint matches 0129 baseline (comments and whitespace ignored)',
         md5(p.norm) = p.exp_body_md5, 'live=' || coalesce(md5(p.norm), 'MISSING') || ' expected=' || p.exp_body_md5),
    (9,  'declares c_active as text[] (the defect) exactly once',
         (split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1) = p.exp_decl) and ((length(p.norm) - length(replace(p.norm, 'c_activeconstant', ''))) / 16) = 1,
         coalesce(split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1), 'MISSING') || ' x' || ((length(p.norm) - length(replace(p.norm, 'c_activeconstant', ''))) / 16)::text),
    (10, 'unchanged use count: d.status = any(c_active) sites and c_active tokens',
         ((length(p.norm) - length(replace(p.norm, 'd.status=any(c_active)', ''))) / 22) = p.n_use and ((length(p.norm) - length(replace(p.norm, 'c_active', ''))) / 8) = p.n_tok,
         ((length(p.norm) - length(replace(p.norm, 'd.status=any(c_active)', ''))) / 22)::text || ' sites / ' || ((length(p.norm) - length(replace(p.norm, 'c_active', ''))) / 8)::text || ' tokens (expected ' || p.n_use::text || ' / ' || p.n_tok::text || ')'),
    (11, 'dispatches.status is never cast to text',
         ((length(p.norm) - length(replace(p.norm, 'status::text', ''))) / 12) = 0 and ((length(p.norm) - length(replace(p.norm, 'status::varchar', ''))) / 15) = 0, ((length(p.norm) - length(replace(p.norm, 'status::text', ''))) / 12)::text)
  ) c(n, title, ok, d)
  union all
  -- global checks
  select 4001, 'CHECK', 'server supports every catalog column this report reads (>= 9.6)',
         case when current_setting('server_version_num')::int >= 90600 then 'PASS' else 'FAIL' end, current_setting('server_version')::text
  union all
  select 4002, 'CHECK', 'dispatches.status is public.dispatch_status',
         case when coalesce((select a.atttypid = to_regtype('public.dispatch_status') from pg_attribute a
                              where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), false) then 'PASS' else 'FAIL' end,
         coalesce((select format_type(a.atttypid, a.atttypmod) from pg_attribute a
                    where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), 'MISSING')::text
  union all
  select 4003, 'CHECK', 'dispatch_status has exactly the expected 10 labels',
         case when coalesce((select array_agg(e.enumlabel::text order by e.enumlabel::text) from pg_enum e
                              where e.enumtypid = to_regtype('public.dispatch_status')) = array['accepted','assigned','at_delivery','at_pickup','cancelled','completed','delivered','en_route_to_delivery','en_route_to_pickup','loaded']::text[], false) then 'PASS' else 'FAIL' end,
         coalesce((select string_agg(e.enumlabel::text, ',' order by e.enumsortorder) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status')), 'MISSING')::text
  union all
  select 4004, 'CHECK', 'dispatch_status contains all 7 active values',
         case when (select count(*) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status') and e.enumlabel::text = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::text[])) = 7 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status') and e.enumlabel::text = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::text[]))::text
  union all
  select 4005, 'CHECK', 'blast radius: number of public functions declaring c_active constant text[] is 2',
         case when (select count(*) from pg_proc x where x.pronamespace = 'public'::regnamespace
                     and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%') = 2 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_proc x where x.pronamespace = 'public'::regnamespace
           and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%')::text
  union all
  select 4006, 'CHECK', '0054 partial unique indexes (driver, truck, trailer) present',
         case when (select count(*) from pg_indexes where schemaname = 'public' and tablename = 'dispatches' and indexname in
                     ('dispatches_active_driver_unique', 'dispatches_active_truck_unique', 'dispatches_active_trailer_unique')) = 3 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_indexes where schemaname = 'public' and tablename = 'dispatches' and indexname like 'dispatches_active_%')::text
  union all
  select 4007, 'CHECK', '0132 trigger dispatches_guard_carrier_scope present on public.dispatches',
         case when exists (select 1 from pg_trigger t where t.tgrelid = to_regclass('public.dispatches')
                            and t.tgname = 'dispatches_guard_carrier_scope' and not t.tgisinternal) then 'PASS' else 'FAIL' end,
         (select count(*) from pg_trigger t where t.tgrelid = to_regclass('public.dispatches') and not t.tgisinternal)::text || ' user triggers on dispatches'
),
verdict as (
  select count(*) filter (where result = 'PASS') as n_pass,
         count(*) filter (where result = 'FAIL') as n_fail,
         count(*) filter (where result = 'INFO') as n_info,
         case when count(*) filter (where result = 'FAIL') = 0 and count(*) filter (where result = 'PASS') > 0 then 0
              else ('PREFLIGHT FAIL: ' || (count(*) filter (where result = 'FAIL'))::text || ' failing check(s). Full report follows.' || E'\n'
                    || string_agg(section || ' | ' || item || ' | ' || result || ' | ' || detail, E'\n' order by ord))::int
         end as gate   -- a deliberate cast error: raises only when a check fails
  from rows
)
select r.ord, r.section, r.item, r.result, r.detail
from rows r cross join verdict v
where v.gate = 0
union all
select 9000, 'RESULT', 'PREFLIGHT: live definitions are the 0129 baseline state', 'PASS',
       v.n_pass::text || ' checks passed, 0 failed, ' || v.n_info::text || ' informational rows'
from verdict v
where v.gate = 0
order by 1;
