-- =============================================================================
-- proposed_0149.sql
-- PROPOSAL 0149 -- NOT APPROVED FOR PRODUCTION. NOT APPLIED. NOT A PRODUCTION MIGRATION.
-- Generated by build.py from supabase/migrations/0129_atomic_dispatch_lifecycle.sql.
--
-- Forward-only corrective proposal for a LIVE defect in two functions defined
-- by 0129: `c_active` is declared `text[]` and compared with
--   d.status = any(c_active)
-- where d.status is public.dispatch_status (an enum) => PostgreSQL raises
--   42883: operator does not exist: dispatch_status = text
-- whenever a statement using it executes (PL/pgSQL type-checks each statement
-- only when it first runs, so CREATE FUNCTION in 0129 succeeded).
-- create_dispatch() reaches it unconditionally at step 5; cancel_dispatch() at
-- its load-revert UPDATE. So every call that reaches those statements fails.
--
-- SCOPE NOTE: this proposal changes NO privileges. Separately, 0135 left
-- `authenticated` with UPDATE on dispatches.notes only, so a DIRECT authenticated
-- call to the SECURITY INVOKER cancel_dispatch() RPC is expected to be refused
-- earlier (42501; confirmed in a disposable database, NOT yet verified in
-- production). That is a separate follow-up blocker, not addressed here; the
-- board path transition_dispatch_status() (SECURITY DEFINER) delegates to
-- cancel_dispatch() and is repaired by this proposal. See README.md, BLOCKER F1.
--
-- THE ONLY SEMANTIC CHANGE: in each of the two functions the declaration
--     c_active constant text[] := array['assigned', ... 'at_delivery'];
-- becomes
--     c_active constant public.dispatch_status[] := array['assigned', ... 'at_delivery']::public.dispatch_status[];
-- Every other byte of each body is the 0129 text (extracted, not retyped).
-- dispatches.status is NOT cast to text (that would defeat the typed 0054
-- partial-unique-index predicates' planner match and the type safety).
--
-- CREATE OR REPLACE keeps the function OIDs, owner, ACL and comment; nothing
-- else is created, altered or dropped (no table/data/enum/index/RLS/policy/
-- trigger/grant/application change).
--
-- NUMBERING: proposal number 0149. It lives ONLY under supabase/proposals/0149/.
-- If 0149 is applied before the separate, unapproved 0148 proposal, that 0148
-- proposal must be renumbered above 0149 before promotion. Do not renumber now.
--
-- One transaction. PHASE 1 fails closed on any drift and writes nothing.
-- =============================================================================
begin;

-- ======================= PHASE 1 -- READ-ONLY PRECONDITIONS ==================
do $mig$
declare r record; v_fail text := '';
begin
  for r in
with expect(idx, fname, sig, rettype, args, descr_md5, body_md5, decl, n_use, n_tok) as (values
    (1, 'create_dispatch', 'public.create_dispatch(uuid,uuid,uuid,uuid,uuid,numeric,text)', 'uuid', 'p_load_id uuid, p_carrier_id uuid, p_truck_id uuid, p_driver_id uuid, p_trailer_id uuid default null::uuid, p_dispatch_fee_percentage numeric default null::numeric, p_notes text default null::text', '932fd6c42b6ea8fe00a6f65c91fa12fa', 'f583544e98d49f21f81c1a6998b02e22', 'text[]', 7, 8),
    (2, 'cancel_dispatch', 'public.cancel_dispatch(uuid,text)', 'void', 'p_dispatch_id uuid, p_reason text default null::text', 'a5a3f91bccd955b92c1ca4e121694f38', '0979e90a1ea4f897088871a57bbb65d9', 'text[]', 1, 2)
),
p as (
  select e.idx, e.fname, e.sig, e.rettype as exp_rettype, e.args as exp_args, e.descr_md5 as exp_descr_md5,
         e.body_md5 as exp_body_md5, e.decl as exp_decl, e.n_use, e.n_tok,
         x.oid, x.oid::regprocedure::text as identity, pg_get_function_identity_arguments(x.oid) as identity_args,
         lower(regexp_replace(pg_get_function_arguments(x.oid), '\s+', ' ', 'g')) as args,
         x.prorettype::regtype::text as rettype, l.lanname::text as lang, x.prosecdef,
         x.provolatile::text as vol, x.proparallel::text as par, x.proisstrict, x.proleakproof,
         x.proconfig, x.proacl, x.proowner::regrole::text as owner,
         obj_description(x.oid, 'pg_proc') as descr, length(x.prosrc) as src_len,
         regexp_replace(lower(regexp_replace(x.prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g') as norm
  from expect e
  left join pg_proc x on x.oid = to_regprocedure(e.sig)
  left join pg_language l on l.oid = x.prolang
),
rows as (
  -- server
  select 100 as ord, 'SERVER' as section, 'server_version' as item, 'INFO' as result, current_setting('server_version')::text as detail
  union all select 101, 'SERVER', 'server_version_num', 'INFO', current_setting('server_version_num')::text
  union all select 102, 'SERVER', 'version()', 'INFO', version()::text
  union all
  -- per-function facts read from the LIVE pg_proc row
  select 1000 + 100 * p.idx + v.n, 'FUNCTION', p.fname || ': ' || v.k, 'INFO', v.d
  from p cross join lateral (values
    (1,  'identity',                  coalesce(p.identity, 'MISSING')::text),
    (2,  'identity arguments',        coalesce(p.identity_args, 'MISSING')::text),
    (3,  'arguments with defaults',   coalesce(p.args, 'MISSING')::text),
    (4,  'returns',                   coalesce(p.rettype, 'MISSING')::text),
    (5,  'language',                  coalesce(p.lang, 'MISSING')::text),
    (6,  'volatility',                coalesce(case p.vol when 'v' then 'VOLATILE' when 's' then 'STABLE' when 'i' then 'IMMUTABLE' else p.vol end, 'MISSING')::text),
    (7,  'parallel safety',           coalesce(case p.par when 'u' then 'UNSAFE' when 's' then 'SAFE' when 'r' then 'RESTRICTED' else p.par end, 'MISSING')::text),
    (8,  'security mode',             coalesce(case when p.prosecdef then 'SECURITY DEFINER' else 'SECURITY INVOKER' end, 'MISSING')::text),
    (9,  'strict / leakproof',        coalesce(p.proisstrict::text || ' / ' || p.proleakproof::text, 'MISSING')::text),
    (10, 'configuration (search_path)', coalesce(p.proconfig::text, '(none)')::text),
    (11, 'owner',                     coalesce(p.owner, 'MISSING')::text),
    (12, 'raw ACL',                   coalesce(p.proacl::text, 'NULL (defaults apply: PUBLIC may execute)')::text),
    (13, 'EXECUTE privilege',         coalesce('authenticated=' || has_function_privilege('authenticated', p.oid, 'EXECUTE')::text
                                        || ' anon=' || has_function_privilege('anon', p.oid, 'EXECUTE')::text
                                        || ' service_role=' || has_function_privilege('service_role', p.oid, 'EXECUTE')::text
                                        || ' PUBLIC=' || (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%'))::text, 'MISSING')::text),
    (14, 'declared c_active type',    coalesce(nullif(split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1), ''), '(no c_active declaration)')::text),
    (15, 'live body md5 (normalised)', coalesce(md5(p.norm) || '  (expected ' || p.exp_body_md5 || ')', 'MISSING')::text),
    (16, 'live source length',        coalesce(p.src_len::text || ' chars', 'MISSING')::text)
  ) v(n, k, d)
  union all
  -- dispatches.status and the enum
  select 2000, 'DISPATCHES', 'dispatches.status column type', 'INFO',
         coalesce((select format_type(a.atttypid, a.atttypmod) from pg_attribute a
                    where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), 'MISSING')::text
  union all
  select 2001, 'DISPATCHES', 'dispatch_status enum values (in sort order)', 'INFO',
         coalesce((select string_agg(e.enumlabel::text, ', ' order by e.enumsortorder) from pg_enum e
                    where e.enumtypid = to_regtype('public.dispatch_status')), 'MISSING')::text
  union all
  select 2002, 'BLAST RADIUS', 'public functions declaring c_active constant text[]', 'INFO',
         coalesce((select string_agg(x.proname::text, ', ' order by x.proname) from pg_proc x
                    where x.pronamespace = 'public'::regnamespace
                      and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%'), '(none)')::text
  union all
  -- per-function checks (PASS / FAIL)
  select 3000 + 100 * p.idx + c.n, 'CHECK', p.fname || ': ' || c.title,
         case when coalesce(c.ok, false) then 'PASS' else 'FAIL' end, coalesce(c.d, 'null')::text
  from p cross join lateral (values
    (1,  'exact signature exists in the live database',
         p.oid is not null, coalesce(p.identity, 'MISSING')::text),
    (2,  'single overload by name',
         (select count(*) from pg_proc y where y.pronamespace = 'public'::regnamespace and y.proname = p.fname) = 1,
         (select count(*) from pg_proc y where y.pronamespace = 'public'::regnamespace and y.proname = p.fname)::text),
    (3,  'plpgsql, SECURITY INVOKER, VOLATILE, PARALLEL UNSAFE, not strict, not leakproof, expected return type',
         p.lang = 'plpgsql' and not p.prosecdef and p.vol = 'v' and p.par = 'u' and not p.proisstrict and not p.proleakproof and p.rettype = p.exp_rettype,
         p.lang || ' definer=' || p.prosecdef::text || ' vol=' || p.vol || ' par=' || p.par || ' returns=' || p.rettype),
    (4,  'search_path is exactly public (sole configuration entry)',
         p.proconfig = array['search_path=public']::text[], coalesce(p.proconfig::text, '(none)')),
    (5,  'argument list and defaults unchanged',
         p.args = p.exp_args, coalesce(p.args, 'MISSING')),
    (6,  'EXECUTE granted to authenticated only (not PUBLIC, anon or service_role)',
         p.proacl is not null
           and has_function_privilege('authenticated', p.oid, 'EXECUTE')
           and not has_function_privilege('anon', p.oid, 'EXECUTE')
           and not has_function_privilege('service_role', p.oid, 'EXECUTE')
           and not exists (select 1 from unnest(p.proacl) a where a::text like '=%'),
         coalesce(p.proacl::text, 'NULL')),
    (7,  'function description unchanged from 0129',
         md5(p.descr) = p.exp_descr_md5, coalesce(md5(p.descr), 'MISSING')),
    (8,  'body fingerprint matches 0129 baseline (comments and whitespace ignored)',
         md5(p.norm) = p.exp_body_md5, 'live=' || coalesce(md5(p.norm), 'MISSING') || ' expected=' || p.exp_body_md5),
    (9,  'declares c_active as text[] (the defect) exactly once',
         (split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1) = p.exp_decl) and ((length(p.norm) - length(replace(p.norm, 'c_activeconstant', ''))) / 16) = 1,
         coalesce(split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1), 'MISSING') || ' x' || ((length(p.norm) - length(replace(p.norm, 'c_activeconstant', ''))) / 16)::text),
    (10, 'unchanged use count: d.status = any(c_active) sites and c_active tokens',
         ((length(p.norm) - length(replace(p.norm, 'd.status=any(c_active)', ''))) / 22) = p.n_use and ((length(p.norm) - length(replace(p.norm, 'c_active', ''))) / 8) = p.n_tok,
         ((length(p.norm) - length(replace(p.norm, 'd.status=any(c_active)', ''))) / 22)::text || ' sites / ' || ((length(p.norm) - length(replace(p.norm, 'c_active', ''))) / 8)::text || ' tokens (expected ' || p.n_use::text || ' / ' || p.n_tok::text || ')'),
    (11, 'dispatches.status is never cast to text',
         ((length(p.norm) - length(replace(p.norm, 'status::text', ''))) / 12) = 0 and ((length(p.norm) - length(replace(p.norm, 'status::varchar', ''))) / 15) = 0, ((length(p.norm) - length(replace(p.norm, 'status::text', ''))) / 12)::text)
  ) c(n, title, ok, d)
  union all
  -- global checks
  select 4001, 'CHECK', 'server supports every catalog column this report reads (>= 9.6)',
         case when current_setting('server_version_num')::int >= 90600 then 'PASS' else 'FAIL' end, current_setting('server_version')::text
  union all
  select 4002, 'CHECK', 'dispatches.status is public.dispatch_status',
         case when coalesce((select a.atttypid = to_regtype('public.dispatch_status') from pg_attribute a
                              where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), false) then 'PASS' else 'FAIL' end,
         coalesce((select format_type(a.atttypid, a.atttypmod) from pg_attribute a
                    where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), 'MISSING')::text
  union all
  select 4003, 'CHECK', 'dispatch_status has exactly the expected 10 labels',
         case when coalesce((select array_agg(e.enumlabel::text order by e.enumlabel::text) from pg_enum e
                              where e.enumtypid = to_regtype('public.dispatch_status')) = array['accepted','assigned','at_delivery','at_pickup','cancelled','completed','delivered','en_route_to_delivery','en_route_to_pickup','loaded']::text[], false) then 'PASS' else 'FAIL' end,
         coalesce((select string_agg(e.enumlabel::text, ',' order by e.enumsortorder) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status')), 'MISSING')::text
  union all
  select 4004, 'CHECK', 'dispatch_status contains all 7 active values',
         case when (select count(*) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status') and e.enumlabel::text = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::text[])) = 7 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status') and e.enumlabel::text = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::text[]))::text
  union all
  select 4005, 'CHECK', 'blast radius: number of public functions declaring c_active constant text[] is 2',
         case when (select count(*) from pg_proc x where x.pronamespace = 'public'::regnamespace
                     and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%') = 2 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_proc x where x.pronamespace = 'public'::regnamespace
           and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%')::text
  union all
  select 4006, 'CHECK', '0054 partial unique indexes (driver, truck, trailer) present',
         case when (select count(*) from pg_indexes where schemaname = 'public' and tablename = 'dispatches' and indexname in
                     ('dispatches_active_driver_unique', 'dispatches_active_truck_unique', 'dispatches_active_trailer_unique')) = 3 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_indexes where schemaname = 'public' and tablename = 'dispatches' and indexname like 'dispatches_active_%')::text
  union all
  select 4007, 'CHECK', '0132 trigger dispatches_guard_carrier_scope present on public.dispatches',
         case when exists (select 1 from pg_trigger t where t.tgrelid = to_regclass('public.dispatches')
                            and t.tgname = 'dispatches_guard_carrier_scope' and not t.tgisinternal) then 'PASS' else 'FAIL' end,
         (select count(*) from pg_trigger t where t.tgrelid = to_regclass('public.dispatches') and not t.tgisinternal)::text || ' user triggers on dispatches'
)
  select ord, section, item, result, detail from rows order by ord
  loop
    if r.result = 'FAIL' then v_fail := v_fail || E'\n  - ' || r.item || ' [' || r.detail || ']'; end if;
  end loop;
  if v_fail <> '' then raise exception '0149 precondition failed (fail closed -- nothing was changed by this step):%', v_fail; end if;
  -- capture owner/ACL/description/config/args so PHASE 3 can prove they are byte-identical after the replace
  perform set_config('td0149.meta', (select md5(string_agg(x.proname::text || '|' || x.proowner::regrole::text || '|' || coalesce(x.proacl::text, '') || '|' || coalesce(obj_description(x.oid, 'pg_proc'), '') || '|' || coalesce(x.proconfig::text, '') || '|' || pg_get_function_arguments(x.oid) || '|' || x.prorettype::regtype::text || '|' || x.provolatile::text || x.proparallel::text || x.prosecdef::text || x.proisstrict::text || x.proleakproof::text, E'\n' order by x.proname)) from pg_proc x where x.oid in (to_regprocedure('public.create_dispatch(uuid,uuid,uuid,uuid,uuid,numeric,text)'), to_regprocedure('public.cancel_dispatch(uuid,text)'))), true);
  raise notice '0149 PHASE 1 preconditions passed.';
end
$mig$;

-- ======================= PHASE 2 -- MUTATION (two CREATE OR REPLACE) =========

create or replace function public.create_dispatch(
  p_load_id                 uuid,
  p_carrier_id              uuid,
  p_truck_id                uuid,
  p_driver_id               uuid,
  p_trailer_id              uuid    default null,
  p_dispatch_fee_percentage numeric default null,
  p_notes                   text    default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $fn$
declare
  c_active constant public.dispatch_status[] := array[
    'assigned','accepted','en_route_to_pickup','at_pickup','loaded',
    'en_route_to_delivery','at_delivery']::public.dispatch_status[];
  v_org         uuid;
  v_load_status text;
  v_dispatch_id uuid;
  v_hit_id      uuid;
  v_hit_ln      text;
  v_hit_label   text;
begin
  -- 1. authenticated
  if auth.uid() is null then
    raise exception 'You must be signed in to create a dispatch.' using errcode = 'TDAUT';
  end if;

  -- 2. role -- exactly the RLS dispatches write tier (0010_rls_policies.sql)
  if not public.has_role(array['owner','admin','dispatcher']::public.org_role[]) then
    raise exception 'Only an owner, admin, or dispatcher can create a dispatch.' using errcode = 'TDROL';
  end if;

  -- 3. lock the load. RLS (loads_select) hides other orgs' loads, so a
  --    cross-tenant p_load_id is simply "not found". organization_id comes
  --    from THIS row -- never from a parameter.
  select l.organization_id, l.status
    into v_org, v_load_status
  from public.loads l
  where l.id = p_load_id
  for update;
  if not found then
    raise exception 'That load could not be found.' using errcode = 'TDLNF';
  end if;

  -- 4. dispatchable status only
  if v_load_status not in ('draft','posted','booked') then
    raise exception 'This load is not in a state that can be dispatched (%).', v_load_status using errcode = 'TDLND', detail = v_load_status;
  end if;

  -- 5. one active dispatch per load. Lock candidate rows so a concurrent
  --    create_dispatch for the SAME load serialises here.
  select d.id into v_dispatch_id
  from public.dispatches d
  where d.load_id = p_load_id and d.status = any(c_active)
  for update
  limit 1;
  if v_dispatch_id is not null then
    raise exception 'This load already has an active dispatch. Open it from the Dispatch Board to make changes, or cancel that dispatch first.'
      using errcode = 'TDDUP', detail = v_dispatch_id::text;
  end if;

  -- 6. active driver / truck / trailer conflicts (specific message; the
  --    0054 partial unique indexes are the final race backstop on step 7).
  select d.id, coalesce(dl.load_number, ''), coalesce(dr.first_name || ' ' || dr.last_name, 'This driver')
    into v_hit_id, v_hit_ln, v_hit_label
  from public.dispatches d
  left join public.loads   dl on dl.id = d.load_id
  left join public.drivers dr on dr.id = d.driver_id
  where d.driver_id = p_driver_id and d.status = any(c_active)
  limit 1;
  if v_hit_id is not null then
    raise exception '% is already assigned to active %.',
      v_hit_label, case when v_hit_ln <> '' then 'load ' || v_hit_ln else 'another dispatch' end
      using errcode = 'TDDRV', detail = v_hit_id::text;
  end if;

  select d.id, coalesce(dl.load_number, ''), coalesce('Truck ' || tk.unit_number, 'This truck')
    into v_hit_id, v_hit_ln, v_hit_label
  from public.dispatches d
  left join public.loads  dl on dl.id = d.load_id
  left join public.trucks tk on tk.id = d.truck_id
  where d.truck_id = p_truck_id and d.status = any(c_active)
  limit 1;
  if v_hit_id is not null then
    raise exception '% is already assigned to active %.',
      v_hit_label, case when v_hit_ln <> '' then 'load ' || v_hit_ln else 'another dispatch' end
      using errcode = 'TDTRK', detail = v_hit_id::text;
  end if;

  if p_trailer_id is not null then
    select d.id, coalesce(dl.load_number, ''), coalesce('Trailer ' || tr.unit_number, 'This trailer')
      into v_hit_id, v_hit_ln, v_hit_label
    from public.dispatches d
    left join public.loads    dl on dl.id = d.load_id
    left join public.trailers tr on tr.id = d.trailer_id
    where d.trailer_id = p_trailer_id and d.status = any(c_active)
    limit 1;
    if v_hit_id is not null then
      raise exception '% is already assigned to active %.',
        v_hit_label, case when v_hit_ln <> '' then 'load ' || v_hit_ln else 'another dispatch' end
        using errcode = 'TDTRL', detail = v_hit_id::text;
    end if;
  end if;

  -- 7. INSERT. Fires (in order): dispatches_guard_org (BEFORE, 0055 --
  --    same-org + same-carrier for every id), dispatches_stamp_proceeds
  --    (BEFORE, 0125), RLS dispatches_insert WITH CHECK (org + role),
  --    dispatches_assign_financial_controller (AFTER, 0125 -- sets
  --    loads.financial_dispatch_id), dispatch_financials_sync (0009/0068).
  insert into public.dispatches (organization_id, load_id, carrier_id, truck_id, driver_id, trailer_id, status)
  values (v_org, p_load_id, p_carrier_id, p_truck_id, p_driver_id, p_trailer_id, 'assigned')
  returning id into v_dispatch_id;

  -- 8. financials + notes (upsert -- mirrors writeDispatchFinancials /
  --    writeDispatchNotes; dispatch_financials_sync recomputes the amounts).
  insert into public.dispatch_financials (dispatch_id, organization_id, dispatch_fee_percentage)
  values (v_dispatch_id, v_org, coalesce(p_dispatch_fee_percentage, 10))
  on conflict (dispatch_id) do update set dispatch_fee_percentage = excluded.dispatch_fee_percentage;

  if p_notes is not null and btrim(p_notes) <> '' then
    insert into public.dispatch_internal_notes (dispatch_id, organization_id, notes)
    values (v_dispatch_id, v_org, p_notes)
    on conflict (dispatch_id) do update set notes = excluded.notes;
  end if;

  -- 9. advance the load
  update public.loads set status = 'dispatched' where id = p_load_id;

  -- 10. audit (same shape as the old app call)
  perform public.log_activity('dispatch'::public.entity_type, v_dispatch_id, 'created', null::jsonb, v_org);

  return v_dispatch_id;

exception
  when unique_violation then
    -- A genuine race between step 6 and step 7 tripped a 0054 partial
    -- unique index. The subtransaction is rolled back; re-derive the
    -- specific holder (fresh read) so the message still names the resource,
    -- else fall back to the same generic "just taken" copy the old
    -- raceLoserConflict() produced.
    select d.id, coalesce(dl.load_number, ''), coalesce(dr.first_name || ' ' || dr.last_name, 'This driver')
      into v_hit_id, v_hit_ln, v_hit_label
    from public.dispatches d
    left join public.loads dl on dl.id = d.load_id
    left join public.drivers dr on dr.id = d.driver_id
    where d.driver_id = p_driver_id and d.status = any(c_active) limit 1;
    if v_hit_id is not null then
      raise exception '% is already assigned to active %.',
        v_hit_label, case when v_hit_ln <> '' then 'load ' || v_hit_ln else 'another dispatch' end
        using errcode = 'TDDRV', detail = v_hit_id::text;
    end if;
    select d.id, coalesce(dl.load_number, ''), coalesce('Truck ' || tk.unit_number, 'This truck')
      into v_hit_id, v_hit_ln, v_hit_label
    from public.dispatches d
    left join public.loads dl on dl.id = d.load_id
    left join public.trucks tk on tk.id = d.truck_id
    where d.truck_id = p_truck_id and d.status = any(c_active) limit 1;
    if v_hit_id is not null then
      raise exception '% is already assigned to active %.',
        v_hit_label, case when v_hit_ln <> '' then 'load ' || v_hit_ln else 'another dispatch' end
        using errcode = 'TDTRK', detail = v_hit_id::text;
    end if;
    if p_trailer_id is not null then
      select d.id, coalesce(dl.load_number, ''), coalesce('Trailer ' || tr.unit_number, 'This trailer')
        into v_hit_id, v_hit_ln, v_hit_label
      from public.dispatches d
      left join public.loads dl on dl.id = d.load_id
      left join public.trailers tr on tr.id = d.trailer_id
      where d.trailer_id = p_trailer_id and d.status = any(c_active) limit 1;
      if v_hit_id is not null then
        raise exception '% is already assigned to active %.',
          v_hit_label, case when v_hit_ln <> '' then 'load ' || v_hit_ln else 'another dispatch' end
          using errcode = 'TDTRL', detail = v_hit_id::text;
      end if;
    end if;
    raise exception 'This assignment was just taken by another dispatch. Please review and choose different equipment/driver.'
      using errcode = 'TDDUP';
end;
$fn$;

create or replace function public.cancel_dispatch(
  p_dispatch_id uuid,
  p_reason      text default null
)
returns void
language plpgsql
security invoker
set search_path = public
as $fn$
declare
  c_active constant public.dispatch_status[] := array[
    'assigned','accepted','en_route_to_pickup','at_pickup','loaded',
    'en_route_to_delivery','at_delivery']::public.dispatch_status[];
  v_org        uuid;
  v_load_id    uuid;
  v_status     text;
  v_notes      text;
  v_cancel_note text;
  v_reason     text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to cancel a dispatch.' using errcode = 'TDAUT';
  end if;
  if not public.has_role(array['owner','admin','dispatcher']::public.org_role[]) then
    raise exception 'Only an owner, admin, or dispatcher can cancel a dispatch.' using errcode = 'TDROL';
  end if;

  -- resolve the load id WITHOUT locking (RLS hides other orgs' dispatches)
  select d.organization_id, d.load_id, d.status
    into v_org, v_load_id, v_status
  from public.dispatches d
  where d.id = p_dispatch_id;
  if not found then
    raise exception 'That dispatch could not be found.' using errcode = 'TDCNF';
  end if;

  -- idempotent: already cancelled -> nothing to do
  if v_status = 'cancelled' then
    return;
  end if;

  -- lock LOAD first (matches create_dispatch's order), then the dispatch
  perform 1 from public.loads where id = v_load_id for update;
  select d.status, d.notes into v_status, v_notes
  from public.dispatches d where d.id = p_dispatch_id for update;

  if v_status = 'cancelled' then
    return; -- raced with another cancel; still a no-op
  end if;
  if v_status in ('delivered','completed') then
    raise exception 'A delivered or completed dispatch cannot be cancelled.' using errcode = 'TDTRM', detail = v_status;
  end if;

  v_cancel_note := '[Cancelled' || case when v_reason is not null then ': ' || v_reason else '' end || ']';

  update public.dispatches
     set status       = 'cancelled',
         notes        = case when v_notes is not null and btrim(v_notes) <> ''
                             then v_notes || E'\n' || v_cancel_note
                             else v_cancel_note end,
         cancelled_at = coalesce(cancelled_at, now())
   where id = p_dispatch_id;

  -- Return the load to 'booked' ONLY when no OTHER active dispatch holds it
  -- and it has not moved past delivery. financial_dispatch_id is left as-is
  -- (historical attribution).
  update public.loads l
     set status = 'booked'
   where l.id = v_load_id
     and l.status not in ('delivered','pod_received','invoiced','closed','cancelled')
     and not exists (
       select 1 from public.dispatches d
       where d.load_id = v_load_id and d.id <> p_dispatch_id and d.status = any(c_active));

  perform public.log_activity(
    'dispatch'::public.entity_type, p_dispatch_id, 'cancelled',
    case when v_reason is not null then jsonb_build_object('reason', v_reason) end,
    v_org);
end;
$fn$;

-- ======================= PHASE 3 -- POSTCONDITIONS =========================
do $mig$
declare r record; v_fail text := '';
begin
  for r in
with expect(idx, fname, sig, rettype, args, descr_md5, body_md5, decl, n_use, n_tok) as (values
    (1, 'create_dispatch', 'public.create_dispatch(uuid,uuid,uuid,uuid,uuid,numeric,text)', 'uuid', 'p_load_id uuid, p_carrier_id uuid, p_truck_id uuid, p_driver_id uuid, p_trailer_id uuid default null::uuid, p_dispatch_fee_percentage numeric default null::numeric, p_notes text default null::text', '932fd6c42b6ea8fe00a6f65c91fa12fa', 'a6034630154d942bdc1d70b6212fa6c0', 'public.dispatch_status[]', 7, 8),
    (2, 'cancel_dispatch', 'public.cancel_dispatch(uuid,text)', 'void', 'p_dispatch_id uuid, p_reason text default null::text', 'a5a3f91bccd955b92c1ca4e121694f38', '00501e2142759e715cdd2571a81fd203', 'public.dispatch_status[]', 1, 2)
),
p as (
  select e.idx, e.fname, e.sig, e.rettype as exp_rettype, e.args as exp_args, e.descr_md5 as exp_descr_md5,
         e.body_md5 as exp_body_md5, e.decl as exp_decl, e.n_use, e.n_tok,
         x.oid, x.oid::regprocedure::text as identity, pg_get_function_identity_arguments(x.oid) as identity_args,
         lower(regexp_replace(pg_get_function_arguments(x.oid), '\s+', ' ', 'g')) as args,
         x.prorettype::regtype::text as rettype, l.lanname::text as lang, x.prosecdef,
         x.provolatile::text as vol, x.proparallel::text as par, x.proisstrict, x.proleakproof,
         x.proconfig, x.proacl, x.proowner::regrole::text as owner,
         obj_description(x.oid, 'pg_proc') as descr, length(x.prosrc) as src_len,
         regexp_replace(lower(regexp_replace(x.prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g') as norm
  from expect e
  left join pg_proc x on x.oid = to_regprocedure(e.sig)
  left join pg_language l on l.oid = x.prolang
),
rows as (
  -- server
  select 100 as ord, 'SERVER' as section, 'server_version' as item, 'INFO' as result, current_setting('server_version')::text as detail
  union all select 101, 'SERVER', 'server_version_num', 'INFO', current_setting('server_version_num')::text
  union all select 102, 'SERVER', 'version()', 'INFO', version()::text
  union all
  -- per-function facts read from the LIVE pg_proc row
  select 1000 + 100 * p.idx + v.n, 'FUNCTION', p.fname || ': ' || v.k, 'INFO', v.d
  from p cross join lateral (values
    (1,  'identity',                  coalesce(p.identity, 'MISSING')::text),
    (2,  'identity arguments',        coalesce(p.identity_args, 'MISSING')::text),
    (3,  'arguments with defaults',   coalesce(p.args, 'MISSING')::text),
    (4,  'returns',                   coalesce(p.rettype, 'MISSING')::text),
    (5,  'language',                  coalesce(p.lang, 'MISSING')::text),
    (6,  'volatility',                coalesce(case p.vol when 'v' then 'VOLATILE' when 's' then 'STABLE' when 'i' then 'IMMUTABLE' else p.vol end, 'MISSING')::text),
    (7,  'parallel safety',           coalesce(case p.par when 'u' then 'UNSAFE' when 's' then 'SAFE' when 'r' then 'RESTRICTED' else p.par end, 'MISSING')::text),
    (8,  'security mode',             coalesce(case when p.prosecdef then 'SECURITY DEFINER' else 'SECURITY INVOKER' end, 'MISSING')::text),
    (9,  'strict / leakproof',        coalesce(p.proisstrict::text || ' / ' || p.proleakproof::text, 'MISSING')::text),
    (10, 'configuration (search_path)', coalesce(p.proconfig::text, '(none)')::text),
    (11, 'owner',                     coalesce(p.owner, 'MISSING')::text),
    (12, 'raw ACL',                   coalesce(p.proacl::text, 'NULL (defaults apply: PUBLIC may execute)')::text),
    (13, 'EXECUTE privilege',         coalesce('authenticated=' || has_function_privilege('authenticated', p.oid, 'EXECUTE')::text
                                        || ' anon=' || has_function_privilege('anon', p.oid, 'EXECUTE')::text
                                        || ' service_role=' || has_function_privilege('service_role', p.oid, 'EXECUTE')::text
                                        || ' PUBLIC=' || (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%'))::text, 'MISSING')::text),
    (14, 'declared c_active type',    coalesce(nullif(split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1), ''), '(no c_active declaration)')::text),
    (15, 'live body md5 (normalised)', coalesce(md5(p.norm) || '  (expected ' || p.exp_body_md5 || ')', 'MISSING')::text),
    (16, 'live source length',        coalesce(p.src_len::text || ' chars', 'MISSING')::text)
  ) v(n, k, d)
  union all
  -- dispatches.status and the enum
  select 2000, 'DISPATCHES', 'dispatches.status column type', 'INFO',
         coalesce((select format_type(a.atttypid, a.atttypmod) from pg_attribute a
                    where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), 'MISSING')::text
  union all
  select 2001, 'DISPATCHES', 'dispatch_status enum values (in sort order)', 'INFO',
         coalesce((select string_agg(e.enumlabel::text, ', ' order by e.enumsortorder) from pg_enum e
                    where e.enumtypid = to_regtype('public.dispatch_status')), 'MISSING')::text
  union all
  select 2002, 'BLAST RADIUS', 'public functions declaring c_active constant text[]', 'INFO',
         coalesce((select string_agg(x.proname::text, ', ' order by x.proname) from pg_proc x
                    where x.pronamespace = 'public'::regnamespace
                      and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%'), '(none)')::text
  union all
  -- per-function checks (PASS / FAIL)
  select 3000 + 100 * p.idx + c.n, 'CHECK', p.fname || ': ' || c.title,
         case when coalesce(c.ok, false) then 'PASS' else 'FAIL' end, coalesce(c.d, 'null')::text
  from p cross join lateral (values
    (1,  'exact signature exists in the live database',
         p.oid is not null, coalesce(p.identity, 'MISSING')::text),
    (2,  'single overload by name',
         (select count(*) from pg_proc y where y.pronamespace = 'public'::regnamespace and y.proname = p.fname) = 1,
         (select count(*) from pg_proc y where y.pronamespace = 'public'::regnamespace and y.proname = p.fname)::text),
    (3,  'plpgsql, SECURITY INVOKER, VOLATILE, PARALLEL UNSAFE, not strict, not leakproof, expected return type',
         p.lang = 'plpgsql' and not p.prosecdef and p.vol = 'v' and p.par = 'u' and not p.proisstrict and not p.proleakproof and p.rettype = p.exp_rettype,
         p.lang || ' definer=' || p.prosecdef::text || ' vol=' || p.vol || ' par=' || p.par || ' returns=' || p.rettype),
    (4,  'search_path is exactly public (sole configuration entry)',
         p.proconfig = array['search_path=public']::text[], coalesce(p.proconfig::text, '(none)')),
    (5,  'argument list and defaults unchanged',
         p.args = p.exp_args, coalesce(p.args, 'MISSING')),
    (6,  'EXECUTE granted to authenticated only (not PUBLIC, anon or service_role)',
         p.proacl is not null
           and has_function_privilege('authenticated', p.oid, 'EXECUTE')
           and not has_function_privilege('anon', p.oid, 'EXECUTE')
           and not has_function_privilege('service_role', p.oid, 'EXECUTE')
           and not exists (select 1 from unnest(p.proacl) a where a::text like '=%'),
         coalesce(p.proacl::text, 'NULL')),
    (7,  'function description unchanged from 0129',
         md5(p.descr) = p.exp_descr_md5, coalesce(md5(p.descr), 'MISSING')),
    (8,  'body fingerprint matches 0149 repaired (comments and whitespace ignored)',
         md5(p.norm) = p.exp_body_md5, 'live=' || coalesce(md5(p.norm), 'MISSING') || ' expected=' || p.exp_body_md5),
    (9,  'declares c_active as public.dispatch_status[] (repaired) exactly once',
         (split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1) = p.exp_decl) and ((length(p.norm) - length(replace(p.norm, 'c_activeconstant', ''))) / 16) = 1,
         coalesce(split_part(split_part(p.norm, 'c_activeconstant', 2), ':=', 1), 'MISSING') || ' x' || ((length(p.norm) - length(replace(p.norm, 'c_activeconstant', ''))) / 16)::text),
    (10, 'unchanged use count: d.status = any(c_active) sites and c_active tokens',
         ((length(p.norm) - length(replace(p.norm, 'd.status=any(c_active)', ''))) / 22) = p.n_use and ((length(p.norm) - length(replace(p.norm, 'c_active', ''))) / 8) = p.n_tok,
         ((length(p.norm) - length(replace(p.norm, 'd.status=any(c_active)', ''))) / 22)::text || ' sites / ' || ((length(p.norm) - length(replace(p.norm, 'c_active', ''))) / 8)::text || ' tokens (expected ' || p.n_use::text || ' / ' || p.n_tok::text || ')'),
    (11, 'dispatches.status is never cast to text',
         ((length(p.norm) - length(replace(p.norm, 'status::text', ''))) / 12) = 0 and ((length(p.norm) - length(replace(p.norm, 'status::varchar', ''))) / 15) = 0, ((length(p.norm) - length(replace(p.norm, 'status::text', ''))) / 12)::text)
  ) c(n, title, ok, d)
  union all
  -- global checks
  select 4001, 'CHECK', 'server supports every catalog column this report reads (>= 9.6)',
         case when current_setting('server_version_num')::int >= 90600 then 'PASS' else 'FAIL' end, current_setting('server_version')::text
  union all
  select 4002, 'CHECK', 'dispatches.status is public.dispatch_status',
         case when coalesce((select a.atttypid = to_regtype('public.dispatch_status') from pg_attribute a
                              where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), false) then 'PASS' else 'FAIL' end,
         coalesce((select format_type(a.atttypid, a.atttypmod) from pg_attribute a
                    where a.attrelid = to_regclass('public.dispatches') and a.attname = 'status' and not a.attisdropped), 'MISSING')::text
  union all
  select 4003, 'CHECK', 'dispatch_status has exactly the expected 10 labels',
         case when coalesce((select array_agg(e.enumlabel::text order by e.enumlabel::text) from pg_enum e
                              where e.enumtypid = to_regtype('public.dispatch_status')) = array['accepted','assigned','at_delivery','at_pickup','cancelled','completed','delivered','en_route_to_delivery','en_route_to_pickup','loaded']::text[], false) then 'PASS' else 'FAIL' end,
         coalesce((select string_agg(e.enumlabel::text, ',' order by e.enumsortorder) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status')), 'MISSING')::text
  union all
  select 4004, 'CHECK', 'dispatch_status contains all 7 active values',
         case when (select count(*) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status') and e.enumlabel::text = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::text[])) = 7 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_enum e where e.enumtypid = to_regtype('public.dispatch_status') and e.enumlabel::text = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::text[]))::text
  union all
  select 4005, 'CHECK', 'blast radius: number of public functions declaring c_active constant text[] is 0',
         case when (select count(*) from pg_proc x where x.pronamespace = 'public'::regnamespace
                     and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%') = 0 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_proc x where x.pronamespace = 'public'::regnamespace
           and regexp_replace(x.prosrc, '\s+', '', 'g') like '%c\_activeconstanttext[]%')::text
  union all
  select 4006, 'CHECK', '0054 partial unique indexes (driver, truck, trailer) present',
         case when (select count(*) from pg_indexes where schemaname = 'public' and tablename = 'dispatches' and indexname in
                     ('dispatches_active_driver_unique', 'dispatches_active_truck_unique', 'dispatches_active_trailer_unique')) = 3 then 'PASS' else 'FAIL' end,
         (select count(*) from pg_indexes where schemaname = 'public' and tablename = 'dispatches' and indexname like 'dispatches_active_%')::text
  union all
  select 4007, 'CHECK', '0132 trigger dispatches_guard_carrier_scope present on public.dispatches',
         case when exists (select 1 from pg_trigger t where t.tgrelid = to_regclass('public.dispatches')
                            and t.tgname = 'dispatches_guard_carrier_scope' and not t.tgisinternal) then 'PASS' else 'FAIL' end,
         (select count(*) from pg_trigger t where t.tgrelid = to_regclass('public.dispatches') and not t.tgisinternal)::text || ' user triggers on dispatches'
  union all
  select 4008, 'CHECK', 'enum-array comparison against live dispatches.status executes (read-only probe)',
         case when (select count(*) from public.dispatches d where d.status = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::public.dispatch_status[])) >= 0 then 'PASS' else 'FAIL' end,
         (select count(*) from public.dispatches d where d.status = any(array['assigned','accepted','en_route_to_pickup','at_pickup','loaded','en_route_to_delivery','at_delivery']::public.dispatch_status[]))::text || ' rows currently in an active status'
)
  select ord, section, item, result, detail from rows order by ord
  loop
    if r.result = 'FAIL' then v_fail := v_fail || E'\n  - ' || r.item || ' [' || r.detail || ']'; end if;
  end loop;
  if v_fail <> '' then raise exception '0149 postcondition failed (fail closed -- nothing was changed by this step):%', v_fail; end if;
  if (select md5(string_agg(x.proname::text || '|' || x.proowner::regrole::text || '|' || coalesce(x.proacl::text, '') || '|' || coalesce(obj_description(x.oid, 'pg_proc'), '') || '|' || coalesce(x.proconfig::text, '') || '|' || pg_get_function_arguments(x.oid) || '|' || x.prorettype::regtype::text || '|' || x.provolatile::text || x.proparallel::text || x.prosecdef::text || x.proisstrict::text || x.proleakproof::text, E'\n' order by x.proname)) from pg_proc x where x.oid in (to_regprocedure('public.create_dispatch(uuid,uuid,uuid,uuid,uuid,numeric,text)'), to_regprocedure('public.cancel_dispatch(uuid,text)'))) is distinct from current_setting('td0149.meta', true) then
    raise exception '0149 postcondition: owner/ACL/description/search_path/argument metadata changed -- CREATE OR REPLACE must preserve all of it.';
  end if;
  raise notice '0149 PHASE 3 postconditions passed.';
end
$mig$;

commit;
