-- =============================================================================
-- post_apply.sql
-- PROPOSAL 0152 -- NOT APPROVED FOR PRODUCTION. NOT APPLIED. NOT A PRODUCTION MIGRATION (lives under supabase/proposals/, not supabase/migrations/).
-- Sequencing: 0130..0147 -> 0149 -> 0150 -> 0151 -> 0152 (this). Current proposal 0148 is unrelated and MUST be
-- renumbered to 0153 or higher before promotion.
--
-- Run AFTER applying 0152 (and any time later). READ-ONLY: ONE select statement. RESULT: rows INFO/PASS + a final RESULT | PASS row, or a
-- raised error ("POST-APPLY 0152 FAIL ...") whose text is the complete report.
-- =============================================================================
with rows as (
  select 100 as ord, 'SERVER' as section, 'server_version' as item, 'INFO' as result, current_setting('server_version')::text as detail
  union all select 110, 'SCHEMA', 'request_fingerprint is a NOT NULL text column on both 0139/0141 ledgers',
         case when (select count(*) from information_schema.columns where table_schema = 'public' and column_name = 'request_fingerprint' and data_type = 'text' and is_nullable = 'NO'
                     and table_name in ('factoring_policy_idempotency', 'factoring_integration_lifecycle_idempotency')) = 2 then 'PASS' else 'FAIL' end, 'catalog'
  union all select 111, 'SCHEMA', 'no ledger row has a NULL fingerprint (impossible by the NOT NULL constraint; must be 0)',
         case when (select count(*) from public.factoring_policy_idempotency where request_fingerprint is null) + (select count(*) from public.factoring_integration_lifecycle_idempotency where request_fingerprint is null) = 0 then 'PASS' else 'FAIL' end, 'ledgers'
  union all select 112, 'SCHEMA', 'new lifecycle fingerprints are sha256; legacy marker occurs only on the two reviewed receipts',
         case when not exists (
           select 1 from public.factoring_integration_lifecycle_idempotency t
           where request_fingerprint !~ '^[0-9a-f]{64}$'
             and not (request_fingerprint = 'legacy-unbound:0152-retirement-v1'
               and action = 'deactivate_relationship'
               and ((target_id = 'fc926ea0-f11c-40fa-941b-afb89aae19de'::uuid and created_at = '2026-09-29 02:31:43.081649+00'::timestamptz)
                 or (target_id = 'd9ddf2b8-8ab5-404a-a906-8a429ca2b608'::uuid and created_at = '2026-09-29 02:40:54.444648+00'::timestamptz))))
           then 'PASS' else 'FAIL' end, 'legacy marker is not a request hash'

  union all select 200, 'FUNCTION', 'reassign_dispatch_resources: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.reassign_dispatch_resources(uuid,uuid,uuid,uuid,text,text,timestamptz)')) = '25feafae360e205e44c89cac6b8af6aa' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.reassign_dispatch_resources(uuid,uuid,uuid,uuid,text,text,timestamptz)')), 'MISSING')
  union all select 201, 'FUNCTION', 'reassign_dispatch_resources: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.reassign_dispatch_resources(uuid,uuid,uuid,uuid,text,text,timestamptz)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.reassign_dispatch_resources(uuid,uuid,uuid,uuid,text,text,timestamptz)')), 'MISSING')
  union all select 203, 'FUNCTION', 'set_carrier_factoring_policy: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.set_carrier_factoring_policy(uuid,public.carrier_factoring_mode,text,timestamptz,text)')) = '8eb6b0a5aafee5842e8c1b56914e1a5a' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.set_carrier_factoring_policy(uuid,public.carrier_factoring_mode,text,timestamptz,text)')), 'MISSING')
  union all select 204, 'FUNCTION', 'set_carrier_factoring_policy: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.set_carrier_factoring_policy(uuid,public.carrier_factoring_mode,text,timestamptz,text)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.set_carrier_factoring_policy(uuid,public.carrier_factoring_mode,text,timestamptz,text)')), 'MISSING')
  union all select 206, 'FUNCTION', 'configure_carrier_factoring_integration: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.configure_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')) = '9d74b0fee3062605df4e9ce7fb84589c' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.configure_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')), 'MISSING')
  union all select 207, 'FUNCTION', 'configure_carrier_factoring_integration: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.configure_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.configure_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')), 'MISSING')
  union all select 209, 'FUNCTION', 'rotate_carrier_factoring_integration: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.rotate_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')) = '79776401048dd10919e1d969fde81545' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.rotate_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')), 'MISSING')
  union all select 210, 'FUNCTION', 'rotate_carrier_factoring_integration: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.rotate_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.rotate_carrier_factoring_integration(uuid,text,text,public.integration_provider,text,text,timestamptz,text)')), 'MISSING')
  union all select 212, 'FUNCTION', 'transition_carrier_factoring_integration_lifecycle: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text,uuid,text,timestamptz,text)')) = '3cf14466f17953413047b3b4ab8d37e4' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text,uuid,text,timestamptz,text)')), 'MISSING')
  union all select 213, 'FUNCTION', 'transition_carrier_factoring_integration_lifecycle: SECURITY DEFINER, pinned search_path, internal-only (authenticated may NOT execute)',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and not has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text,uuid,text,timestamptz,text)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text,uuid,text,timestamptz,text)')), 'MISSING')
  union all select 215, 'FUNCTION', 'deactivate_factoring_relationship: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.deactivate_factoring_relationship(uuid,text,timestamptz,text,boolean)')) = '532c14e3edb67e56e972adfdf9fdf79c' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.deactivate_factoring_relationship(uuid,text,timestamptz,text,boolean)')), 'MISSING')
  union all select 216, 'FUNCTION', 'deactivate_factoring_relationship: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.deactivate_factoring_relationship(uuid,text,timestamptz,text,boolean)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.deactivate_factoring_relationship(uuid,text,timestamptz,text,boolean)')), 'MISSING')
  union all select 218, 'FUNCTION', 'review_legacy_invoice_carrier_migration: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.review_legacy_invoice_carrier_migration(uuid,text,text,timestamptz,text)')) = '9e15d52c59ed3ea03491a8737dce273d' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.review_legacy_invoice_carrier_migration(uuid,text,text,timestamptz,text)')), 'MISSING')
  union all select 219, 'FUNCTION', 'review_legacy_invoice_carrier_migration: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.review_legacy_invoice_carrier_migration(uuid,text,text,timestamptz,text)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.review_legacy_invoice_carrier_migration(uuid,text,text,timestamptz,text)')), 'MISSING')
  union all select 221, 'FUNCTION', 'update_carrier_invoice_draft: body is the reviewed 0152 definition',
         case when (select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.update_carrier_invoice_draft(uuid,jsonb,timestamptz,text,text)')) = '58037929fdf3093a3f5ac72ef72a277d' then 'PASS' else 'FAIL' end, coalesce((select md5(regexp_replace(lower(regexp_replace(prosrc, '--[^\n]*', '', 'g')), '\s+', '', 'g')) from pg_proc where oid = to_regprocedure('public.update_carrier_invoice_draft(uuid,jsonb,timestamptz,text,text)')), 'MISSING')
  union all select 222, 'FUNCTION', 'update_carrier_invoice_draft: SECURITY DEFINER, pinned search_path, EXECUTE for authenticated, none for PUBLIC',
         case when (select p.prosecdef and p.proconfig::text = '{"search_path=pg_catalog, public"}' and has_function_privilege('authenticated', p.oid, 'execute')
                           and not (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.update_carrier_invoice_draft(uuid,jsonb,timestamptz,text,text)')) then 'PASS' else 'FAIL' end,
         coalesce((select coalesce(p.proacl::text, 'NULL') from pg_proc p where p.oid = to_regprocedure('public.update_carrier_invoice_draft(uuid,jsonb,timestamptz,text,text)')), 'MISSING')
  union all select 400, 'PRIVILEGE', 'internal helper public._issue_dispatch_service_invoice_internal is executable by NO client role and NOT service_role', case when to_regprocedure('public._issue_dispatch_service_invoice_internal(uuid, public.carrier_invoices, uuid, uuid, text, text, text, integer, text)') is not null and not has_function_privilege('service_role', to_regprocedure('public._issue_dispatch_service_invoice_internal(uuid, public.carrier_invoices, uuid, uuid, text, text, text, integer, text)'), 'execute') and not has_function_privilege('authenticated', to_regprocedure('public._issue_dispatch_service_invoice_internal(uuid, public.carrier_invoices, uuid, uuid, text, text, text, integer, text)'), 'execute') and not has_function_privilege('anon', to_regprocedure('public._issue_dispatch_service_invoice_internal(uuid, public.carrier_invoices, uuid, uuid, text, text, text, integer, text)'), 'execute') and not (select (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public._issue_dispatch_service_invoice_internal(uuid, public.carrier_invoices, uuid, uuid, text, text, text, integer, text)')) then 'PASS' else 'FAIL' end, coalesce((select coalesce(proacl::text, 'NULL') from pg_proc where oid = to_regprocedure('public._issue_dispatch_service_invoice_internal(uuid, public.carrier_invoices, uuid, uuid, text, text, text, integer, text)')), 'MISSING')
  union all select 402, 'PRIVILEGE', 'internal helper public.transition_carrier_factoring_integration_lifecycle is executable by NO client role and NOT service_role', case when to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text, uuid, text, timestamptz, text)') is not null and not has_function_privilege('service_role', to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text, uuid, text, timestamptz, text)'), 'execute') and not has_function_privilege('authenticated', to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text, uuid, text, timestamptz, text)'), 'execute') and not has_function_privilege('anon', to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text, uuid, text, timestamptz, text)'), 'execute') and not (select (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text, uuid, text, timestamptz, text)')) then 'PASS' else 'FAIL' end, coalesce((select coalesce(proacl::text, 'NULL') from pg_proc where oid = to_regprocedure('public.transition_carrier_factoring_integration_lifecycle(text, uuid, text, timestamptz, text)')), 'MISSING')
  union all select 404, 'PRIVILEGE', 'internal helper public._generate_carrier_invoice_payment_number_internal is executable by NO client role and NOT service_role', case when to_regprocedure('public._generate_carrier_invoice_payment_number_internal()') is not null and not has_function_privilege('service_role', to_regprocedure('public._generate_carrier_invoice_payment_number_internal()'), 'execute') and not has_function_privilege('authenticated', to_regprocedure('public._generate_carrier_invoice_payment_number_internal()'), 'execute') and not has_function_privilege('anon', to_regprocedure('public._generate_carrier_invoice_payment_number_internal()'), 'execute') and not (select (p.proacl is null or exists (select 1 from unnest(p.proacl) a where a::text like '=%')) from pg_proc p where p.oid = to_regprocedure('public._generate_carrier_invoice_payment_number_internal()')) then 'PASS' else 'FAIL' end, coalesce((select coalesce(proacl::text, 'NULL') from pg_proc where oid = to_regprocedure('public._generate_carrier_invoice_payment_number_internal()')), 'MISSING')
),
verdict as (
  select count(*) filter (where result = 'PASS') as n_pass, count(*) filter (where result = 'FAIL') as n_fail, count(*) filter (where result = 'INFO') as n_info,
         case when count(*) filter (where result = 'FAIL') = 0 and count(*) filter (where result = 'PASS') > 0 then 0
              else ('POST-APPLY 0152 FAIL: ' || (count(*) filter (where result = 'FAIL'))::text || ' failing check(s). Full report follows.' || E'\n'
                    || string_agg(section || ' | ' || item || ' | ' || result || ' | ' || detail, E'\n' order by ord))::int
         end as gate   -- a deliberate cast error: raises only when a check fails
  from rows
)
select r.ord, r.section, r.item, r.result, r.detail from rows r cross join verdict v where v.gate = 0
union all
select 9000, 'RESULT', 'POST-APPLY 0152: replay authorization + request binding + helper privileges in place', 'PASS', v.n_pass::text || ' checks passed, 0 failed, ' || v.n_info::text || ' informational rows' from verdict v where v.gate = 0
order by 1;
