-- =============================================================================
-- probe_safe_0144_0147.sql -- PROPOSAL 0152: runtime probes for every externally executable idempotent RPC of 0144-0147 classified SAFE
-- (GENERATED by build.py). NOT APPROVED FOR PRODUCTION. NOT A MIGRATION. DISPOSABLE SCRATCH DATABASE ONLY.
-- Current proposal 0148 must be renumbered to 0153 or higher before promotion. Appended by tests.py to a copy of TEST_0147 (which supplies the
-- 0130..0147 chain and the stub organizations/users); builds its own carriers, loads, drafts, issued invoices, payments and agreements.
-- Probes per RPC: original call, same-user replay, other authorized user, unauthenticated, unauthorized same-org role, foreign org with the real key and a
-- wrong key, removed / moved / downgraded member, changed request, same key on another target, same key in another org (where a foreign target exists),
-- failed transaction (fault injected at the ledger insert, AFTER the business writes), retry, further retry. Ledger, audit and business-table counts and
-- a business-table fingerprint are recorded after every call.
-- =============================================================================
\set ON_ERROR_STOP on
reset role;
select set_config('test.current_uid', 'aaaa0000-0000-0000-0000-000000000001', false);
create schema pb;
grant usage on schema pb to authenticated;
create table pb.tgt (tag text primary key, id uuid not null, t0 timestamptz, aux uuid);
create table pb.rec (seq bigserial primary key, kind text, tag text, outcome text, msg text, n_led bigint, n_act bigint, n_biz bigint, biz text);
grant select, insert on pb.tgt, pb.rec to authenticated;
grant usage on sequence pb.rec_seq_seq to authenticated;
create function pb.id(p text) returns uuid language sql immutable as $$ select md5('pb0152:' || p)::uuid $$;
insert into auth.users (id) values ('aaaa0000-0000-0000-0000-000000000002') on conflict do nothing;
insert into public.profiles (id, organization_id, full_name, email, role) values ('aaaa0000-0000-0000-0000-000000000002', '11111111-1111-1111-1111-111111111111', 'Admin A', 'admina@example.com', 'admin') on conflict do nothing;
insert into public.brokers (id, organization_id, company_name) values (pb.id('brokerB'), '22222222-2222-2222-2222-222222222222', 'Probe Broker B') on conflict do nothing;
update public.organizations set remittance_instructions = coalesce(remittance_instructions, 'Probe remittance') where id = '11111111-1111-1111-1111-111111111111';

-- fixture builders (superuser, owner identity; all rows are created through the real tables / RPCs)
create function pb.mk_carrier(p_org uuid, p_tag text, p_link boolean) returns uuid language plpgsql as $$
declare v uuid := pb.id('carrier:' || p_tag);
begin
  insert into public.carriers (id, organization_id, legal_name, address_line1, city, state, postal_code, email, is_active)
  values (v, p_org, 'PB Carrier ' || p_tag, '1 Probe St', 'Dallas', 'TX', '75201', 'pb@example.com', true);
  update public.carriers set invoice_code = translate(upper(substr(md5(p_tag), 1, 6)), '0123456789', 'GHIJKLMNOP'), factoring_mode = 'direct' where id = v;
  if p_link then
    insert into public.carrier_brokers (id, organization_id, carrier_id, broker_id, status, billing_email, payment_terms_days, factoring_eligible, activated_at, activated_by)
    values (pb.id('cb:' || p_tag), p_org, v, 'a0b00000-0000-0000-0000-000000000001', 'active', 'ap@brokera.example', 30, true, now(), 'aaaa0000-0000-0000-0000-000000000001');
  end if;
  return v;
end $$;
create function pb.mk_draft(p_carrier uuid, p_tag text, p_with_load boolean) returns uuid language plpgsql as $$
declare v_inv uuid; v_load uuid := pb.id('load:' || p_tag);
begin
  insert into public.carrier_invoices (organization_id, invoice_document_type, carrier_id, recipient_type, recipient_broker_id, created_by)
  values ('11111111-1111-1111-1111-111111111111', 'carrier_freight_invoice', p_carrier, 'broker', 'a0b00000-0000-0000-0000-000000000001', 'aaaa0000-0000-0000-0000-000000000001') returning id into v_inv;
  if p_with_load then
    insert into public.loads (id, organization_id, load_number, broker_id, status, rate) values (v_load, '11111111-1111-1111-1111-111111111111', 'LD-PB-' || p_tag, 'a0b00000-0000-0000-0000-000000000001', 'delivered', 1000.00);
    update public.loads set carrier_id = p_carrier, carrier_resolution = 'resolved' where id = v_load;
    insert into public.load_stops (organization_id, load_id, stop_type, stop_sequence, facility_name, city, state, scheduled_at) values
      ('11111111-1111-1111-1111-111111111111', v_load, 'pickup', 1, 'Shipper PB', 'Dallas', 'TX', now() - interval '3 days'), ('11111111-1111-1111-1111-111111111111', v_load, 'delivery', 2, 'Receiver PB', 'Houston', 'TX', now() - interval '1 day');
    insert into public.carrier_invoice_line_items (organization_id, invoice_id, description, quantity, unit_price, line_type, source_load_id) values ('11111111-1111-1111-1111-111111111111', v_inv, 'Freight PB ' || p_tag, 1, 1000.00, 'freight_charge', v_load);
    insert into public.carrier_invoice_loads (organization_id, invoice_id, load_id) values ('11111111-1111-1111-1111-111111111111', v_inv, v_load);
  end if;
  return v_inv;
end $$;
create function pb.mk_issued(p_tag text) returns uuid language plpgsql as $$
declare v_car uuid := pb.mk_carrier('11111111-1111-1111-1111-111111111111', 'iv:' || p_tag, true); v_inv uuid; v jsonb;
begin
  v_inv := pb.mk_draft(v_car, 'iv:' || p_tag, true);
  v := public.issue_carrier_invoice(v_inv, (select updated_at from public.carrier_invoices where id = v_inv), 'fixture issuance', 'pbfix-issue-' || p_tag);
  if v ->> 'code' <> 'ISSUED' then raise exception 'probe fixture: issuance failed for %: %', p_tag, v; end if;
  return v_inv;
end $$;
create function pb.mk_agreement(p_tag text) returns uuid language plpgsql as $$
declare v_car uuid := pb.mk_carrier('11111111-1111-1111-1111-111111111111', 'ag:' || p_tag, false); v jsonb;
begin
  v := public.create_carrier_dispatch_service_agreement(v_car, 'FIX-' || p_tag, 'fixture agreement', 'pbfix-agr-' || p_tag);
  if v ->> 'code' <> 'CREATED' then raise exception 'probe fixture: agreement failed for %: %', p_tag, v; end if;
  return (v ->> 'agreement_id')::uuid;
end $$;
create function pb.mk_version(p_agreement uuid, p_tag text, p_approve boolean) returns uuid language plpgsql as $$
declare v jsonb; ver uuid;
begin
  v := public.create_carrier_dispatch_service_agreement_version(p_agreement, 'flat_per_load', null, 50.00, null, null, 'USD', 15, current_date - 10, null, 'fixture version', 'pbfix-ver-' || p_tag);
  if v ->> 'code' <> 'CREATED' then raise exception 'probe fixture: version failed for %: %', p_tag, v; end if;
  ver := (v ->> 'version_id')::uuid;
  if p_approve then
    v := public.approve_carrier_dispatch_service_agreement_version(ver, (select updated_at from public.carrier_dispatch_service_agreement_versions where id = ver), 'fixture approval', 'pbfix-apv-' || p_tag);
    if v ->> 'code' <> 'APPROVED' then raise exception 'probe fixture: approval failed for %: %', p_tag, v; end if;
  end if;
  return ver;
end $$;

do $t$
declare g int; car uuid; v uuid; inv uuid; pay jsonb; ag uuid;
begin
  for g in 1..3 loop
    car := pb.mk_carrier('11111111-1111-1111-1111-111111111111', 'cdr' || g, false);
    insert into pb.tgt values ('cdr:' || g, car, null, 'a0b00000-0000-0000-0000-000000000001');
    inv := pb.mk_draft(pb.mk_carrier('11111111-1111-1111-1111-111111111111', 'ddr' || g, false), 'ddr' || g, false);
    insert into pb.tgt values ('ddr:' || g, inv, (select updated_at from public.carrier_invoices where id = inv), null);
    inv := pb.mk_draft(pb.mk_carrier('11111111-1111-1111-1111-111111111111', 'iss' || g, true), 'iss' || g, true);
    insert into pb.tgt values ('iss:' || g, inv, (select updated_at from public.carrier_invoices where id = inv), null);
    inv := pb.mk_issued('pay' || g);
    insert into pb.tgt values ('pay:' || g, inv, (select updated_at from public.carrier_invoices where id = inv), null);
    inv := pb.mk_issued('vpay' || g);
    pay := public.record_carrier_invoice_payment(inv, 100.00, current_date, 'ach', 'FIXREF', (select updated_at from public.carrier_invoices where id = inv), 'fixture payment', 'pbfix-pay-' || g);
    if pay ->> 'code' <> 'PAYMENT_RECORDED' then raise exception 'probe fixture: payment failed: %', pay; end if;
    insert into pb.tgt values ('vpay:' || g, (pay ->> 'payment_id')::uuid, (select updated_at from public.carrier_invoice_payments where id = (pay ->> 'payment_id')::uuid), null);
    car := pb.mk_carrier('11111111-1111-1111-1111-111111111111', 'agr' || g, false);
    insert into pb.tgt values ('agr:' || g, car, null, null);
    ag := pb.mk_agreement('agv' || g);
    insert into pb.tgt values ('agv:' || g, ag, null, null);
    v := pb.mk_version(pb.mk_agreement('apv' || g), 'apv' || g, false);
    insert into pb.tgt values ('apv:' || g, v, (select updated_at from public.carrier_dispatch_service_agreement_versions where id = v), null);
    v := pb.mk_version(pb.mk_agreement('dav' || g), 'dav' || g, true);
    insert into pb.tgt values ('dav:' || g, v, (select updated_at from public.carrier_dispatch_service_agreement_versions where id = v), null);
    ag := pb.mk_agreement('dag' || g);
    insert into pb.tgt values ('dag:' || g, ag, (select updated_at from public.carrier_dispatch_service_agreements where id = ag), null);
  end loop;
  insert into public.carriers (id, organization_id, legal_name, address_line1, city, state, postal_code, email, is_active) values (pb.id('carrier:cdrx'), '22222222-2222-2222-2222-222222222222', 'PB Carrier B', '1 B St', 'Reno', 'NV', '89501', 'pbb@example.com', true);
  insert into pb.tgt values ('cdr:x1', pb.id('carrier:cdrx'), null, pb.id('brokerB'));
  insert into public.carriers (id, organization_id, legal_name, address_line1, city, state, postal_code, email, is_active) values (pb.id('carrier:agrx'), '22222222-2222-2222-2222-222222222222', 'PB Carrier B2', '2 B St', 'Reno', 'NV', '89501', 'pbb2@example.com', true);
  insert into pb.tgt values ('agr:x1', pb.id('carrier:agrx'), null, null);
  insert into public.carrier_invoices (id, organization_id, invoice_document_type, carrier_id, recipient_type, recipient_broker_id, created_by)
  values (pb.id('draftB'), '22222222-2222-2222-2222-222222222222', 'carrier_freight_invoice', pb.id('carrier:cdrx'), 'broker', pb.id('brokerB'), 'bbbb0000-0000-0000-0000-000000000001');
  insert into pb.tgt values ('ddr:x1', pb.id('draftB'), (select updated_at from public.carrier_invoices where id = pb.id('draftB')), null);
end $t$;

create function pb.led(p_kind text) returns bigint language plpgsql stable security definer as $$
declare n bigint;
begin execute format('select count(*) from public.%I', case p_kind
      when 'cdr' then 'carrier_invoice_draft_create_idempotency'
      when 'ddr' then 'carrier_invoice_draft_delete_idempotency'
      when 'iss' then 'carrier_invoice_lifecycle_idempotency'
      when 'pay' then 'carrier_invoice_lifecycle_idempotency'
      when 'vpay' then 'carrier_invoice_lifecycle_idempotency'
      when 'agr' then 'carrier_dispatch_service_agreement_idempotency'
      when 'agv' then 'carrier_dispatch_service_agreement_idempotency'
      when 'apv' then 'carrier_dispatch_service_agreement_idempotency'
      when 'dav' then 'carrier_dispatch_service_agreement_idempotency'
      when 'dag' then 'carrier_dispatch_service_agreement_idempotency'
    end) into n; return n; end $$;
create function pb.biz(p_kind text, out n bigint, out h text) language plpgsql stable security definer as $$
begin execute format($f$select count(*), md5(coalesce(string_agg(to_jsonb(t)::text, '|' order by t.id), '')) from public.%I t$f$, case p_kind
      when 'cdr' then 'carrier_invoices'
      when 'ddr' then 'carrier_invoices'
      when 'iss' then 'carrier_invoices'
      when 'pay' then 'carrier_invoice_payments'
      when 'vpay' then 'carrier_invoice_payments'
      when 'agr' then 'carrier_dispatch_service_agreements'
      when 'agv' then 'carrier_dispatch_service_agreement_versions'
      when 'apv' then 'carrier_dispatch_service_agreement_versions'
      when 'dav' then 'carrier_dispatch_service_agreement_versions'
      when 'dag' then 'carrier_dispatch_service_agreements'
    end) into n, h; end $$;
create function pb.act() returns bigint language sql stable security definer as $$ select count(*) from public.activity_logs $$;
grant execute on function pb.led(text), pb.biz(text), pb.act() to authenticated;

create function pb.call(p_kind text, p_user text, p_target text, p_key text, p_variant text default 'a', out outcome text, out msg text) language plpgsql as $$
declare t pb.tgt; r jsonb;
begin
  perform set_config('test.current_uid', coalesce(p_user, ''), false);
  select * into t from pb.tgt where tag = p_kind || ':' || p_target;
  begin
    if p_kind = 'cdr' then r := public.create_carrier_invoice_draft('carrier_freight_invoice', t.id, 'broker', t.aux, null, 'USD', 30, null, 'notes ' || p_variant, 'a valid reason', p_key);
    elsif p_kind = 'ddr' then r := public.delete_carrier_invoice_draft(t.id, t.t0, 'a valid reason ' || p_variant, p_key);
    elsif p_kind = 'iss' then r := public.issue_carrier_invoice(t.id, t.t0, 'a valid reason ' || p_variant, p_key);
    elsif p_kind = 'pay' then r := public.record_carrier_invoice_payment(t.id, case p_variant when 'a' then 100.00 else 101.00 end, current_date, 'ach', 'REF', t.t0, 'a valid reason', p_key);
    elsif p_kind = 'vpay' then r := public.void_carrier_invoice_payment(t.id, t.t0, 'a valid reason ' || p_variant, p_key);
    elsif p_kind = 'agr' then r := public.create_carrier_dispatch_service_agreement(t.id, 'AGR-' || p_target || '-' || p_variant, 'a valid reason', p_key);
    elsif p_kind = 'agv' then r := public.create_carrier_dispatch_service_agreement_version(t.id, 'flat_per_load', null, case p_variant when 'a' then 50.00 else 60.00 end, null, null, 'USD', 15, current_date - 10, null, 'a valid reason', p_key);
    elsif p_kind = 'apv' then r := public.approve_carrier_dispatch_service_agreement_version(t.id, t.t0, 'a valid reason ' || p_variant, p_key);
    elsif p_kind = 'dav' then r := public.deactivate_carrier_dispatch_service_agreement_version(t.id, t.t0, 'a valid reason ' || p_variant, p_key);
    elsif p_kind = 'dag' then r := public.deactivate_carrier_dispatch_service_agreement(t.id, t.t0, 'a valid reason ' || p_variant, p_key);
    else raise exception 'unknown probe kind %', p_kind; end if;
    outcome := case when (r ->> 'success') = 'true' then 'S' else 'F:' || coalesce(r ->> 'code', 'unspecified') end;
    msg := coalesce(r ->> 'message', '');
  exception when others then
    get stacked diagnostics outcome := returned_sqlstate, msg := message_text;
    outcome := 'X:' || outcome;
  end;
  msg := regexp_replace(msg, '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', '<uuid>', 'g');
end $$;
grant execute on function pb.call(text, text, text, text, text) to authenticated;
create function pb.step(p_kind text, p_tag text, p_user text, p_target text, p_key text, p_variant text default 'a') returns void language plpgsql as $$
declare o record; b record;
begin
  select * into o from pb.call(p_kind, p_user, p_target, p_key, p_variant);
  select * into b from pb.biz(p_kind);
  insert into pb.rec (kind, tag, outcome, msg, n_led, n_act, n_biz, biz) values (p_kind, p_tag, o.outcome, o.msg, pb.led(p_kind), pb.act(), b.n, b.h);
end $$;
grant execute on function pb.step(text, text, text, text, text, text) to authenticated;
create function pb.snap(p_kind text) returns void language plpgsql as $$
declare b record;
begin select * into b from pb.biz(p_kind); insert into pb.rec (kind, tag, outcome, msg, n_led, n_act, n_biz, biz) values (p_kind, 'pre', '', '', pb.led(p_kind), pb.act(), b.n, b.h); end $$;
grant execute on function pb.snap(text) to authenticated;

create function pb.boom() returns trigger language plpgsql as $$
begin
  if current_setting('td0149.boom', true) = tg_table_name then raise exception 'FORCED downstream failure in %', tg_table_name using errcode = 'P0F11'; end if;
  return new;
end $$;
create trigger pb_boom before insert on public.carrier_invoice_lifecycle_idempotency for each row execute function pb.boom();
create trigger pb_boom before insert on public.carrier_dispatch_service_agreement_idempotency for each row execute function pb.boom();
create trigger pb_boom before insert on public.carrier_invoice_draft_create_idempotency for each row execute function pb.boom();
create trigger pb_boom before insert on public.carrier_invoice_draft_delete_idempotency for each row execute function pb.boom();

-- ---- cdr: create_carrier_invoice_draft (0147)
select pb.snap('cdr');
set role authenticated;
select pb.step('cdr', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's2_other_authorized_replay', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's3_unauthenticated', null, '1', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's4_unauthorized_role', 'eeee0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('cdr', 's7_removed_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('cdr', 's8_moved_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('cdr', 's9_downgraded_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'a');
reset role;
update public.profiles set role = 'accountant' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('cdr', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-cdr-1', 'b');
select pb.step('cdr', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-cdr-1', 'a');
select pb.step('cdr', 's12_same_key_other_org', 'bbbb0000-0000-0000-0000-000000000001', 'x1', 'KEY-cdr-1', 'a');
reset role;
set td0149.boom = 'carrier_invoice_draft_create_idempotency';
set role authenticated;
select pb.step('cdr', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-cdr-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('cdr', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-cdr-3', 'a');
select pb.step('cdr', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-cdr-3', 'a');
reset role;

-- ---- ddr: delete_carrier_invoice_draft (0147)
select pb.snap('ddr');
set role authenticated;
select pb.step('ddr', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's2_other_authorized_replay', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's3_unauthenticated', null, '1', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('ddr', 's7_removed_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('ddr', 's8_moved_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('ddr', 's9_downgraded_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'a');
reset role;
update public.profiles set role = 'accountant' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('ddr', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-ddr-1', 'b');
select pb.step('ddr', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-ddr-1', 'a');
select pb.step('ddr', 's12_same_key_other_org', 'bbbb0000-0000-0000-0000-000000000001', 'x1', 'KEY-ddr-1', 'a');
reset role;
set td0149.boom = 'carrier_invoice_draft_delete_idempotency';
set role authenticated;
select pb.step('ddr', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-ddr-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('ddr', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-ddr-3', 'a');
select pb.step('ddr', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-ddr-3', 'a');
reset role;

-- ---- iss: issue_carrier_invoice (0146)
select pb.snap('iss');
set role authenticated;
select pb.step('iss', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
select pb.step('iss', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
select pb.step('iss', 's2_other_authorized_replay', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
select pb.step('iss', 's3_unauthenticated', null, '1', 'KEY-iss-1', 'a');
select pb.step('iss', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
select pb.step('iss', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
select pb.step('iss', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('iss', 's7_removed_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('iss', 's8_moved_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('iss', 's9_downgraded_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'a');
reset role;
update public.profiles set role = 'accountant' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('iss', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-iss-1', 'b');
select pb.step('iss', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-iss-1', 'a');
reset role;
set td0149.boom = 'carrier_invoice_lifecycle_idempotency';
set role authenticated;
select pb.step('iss', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-iss-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('iss', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-iss-3', 'a');
select pb.step('iss', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-iss-3', 'a');
reset role;

-- ---- pay: record_carrier_invoice_payment (0146)
select pb.snap('pay');
set role authenticated;
select pb.step('pay', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
select pb.step('pay', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
select pb.step('pay', 's2_other_authorized_replay', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
select pb.step('pay', 's3_unauthenticated', null, '1', 'KEY-pay-1', 'a');
select pb.step('pay', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
select pb.step('pay', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
select pb.step('pay', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('pay', 's7_removed_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('pay', 's8_moved_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('pay', 's9_downgraded_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'a');
reset role;
update public.profiles set role = 'accountant' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('pay', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-pay-1', 'b');
select pb.step('pay', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-pay-1', 'a');
reset role;
set td0149.boom = 'carrier_invoice_lifecycle_idempotency';
set role authenticated;
select pb.step('pay', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-pay-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('pay', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-pay-3', 'a');
select pb.step('pay', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-pay-3', 'a');
reset role;

-- ---- vpay: void_carrier_invoice_payment (0146)
select pb.snap('vpay');
set role authenticated;
select pb.step('vpay', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
select pb.step('vpay', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
select pb.step('vpay', 's2_other_authorized_replay', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
select pb.step('vpay', 's3_unauthenticated', null, '1', 'KEY-vpay-1', 'a');
select pb.step('vpay', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
select pb.step('vpay', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
select pb.step('vpay', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('vpay', 's7_removed_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('vpay', 's8_moved_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('vpay', 's9_downgraded_member', 'cccc0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'a');
reset role;
update public.profiles set role = 'accountant' where id = 'cccc0000-0000-0000-0000-000000000001';
set role authenticated;
select pb.step('vpay', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-vpay-1', 'b');
select pb.step('vpay', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-vpay-1', 'a');
reset role;
set td0149.boom = 'carrier_invoice_lifecycle_idempotency';
set role authenticated;
select pb.step('vpay', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-vpay-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('vpay', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-vpay-3', 'a');
select pb.step('vpay', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-vpay-3', 'a');
reset role;

-- ---- agr: create_carrier_dispatch_service_agreement (0145)
select pb.snap('agr');
set role authenticated;
select pb.step('agr', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-agr-1', 'a');
select pb.step('agr', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-agr-1', 'a');
select pb.step('agr', 's2_other_authorized_replay', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agr-1', 'a');
select pb.step('agr', 's3_unauthenticated', null, '1', 'KEY-agr-1', 'a');
select pb.step('agr', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-agr-1', 'a');
select pb.step('agr', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-agr-1', 'a');
select pb.step('agr', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-agr-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agr', 's7_removed_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agr-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agr', 's8_moved_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agr-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agr', 's9_downgraded_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agr-1', 'a');
reset role;
update public.profiles set role = 'admin' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agr', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-agr-1', 'b');
select pb.step('agr', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-agr-1', 'a');
select pb.step('agr', 's12_same_key_other_org', 'bbbb0000-0000-0000-0000-000000000001', 'x1', 'KEY-agr-1', 'a');
reset role;
set td0149.boom = 'carrier_dispatch_service_agreement_idempotency';
set role authenticated;
select pb.step('agr', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-agr-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('agr', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-agr-3', 'a');
select pb.step('agr', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-agr-3', 'a');
reset role;

-- ---- agv: create_carrier_dispatch_service_agreement_version (0145)
select pb.snap('agv');
set role authenticated;
select pb.step('agv', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-agv-1', 'a');
select pb.step('agv', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-agv-1', 'a');
select pb.step('agv', 's2_other_authorized_replay', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agv-1', 'a');
select pb.step('agv', 's3_unauthenticated', null, '1', 'KEY-agv-1', 'a');
select pb.step('agv', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-agv-1', 'a');
select pb.step('agv', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-agv-1', 'a');
select pb.step('agv', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-agv-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agv', 's7_removed_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agv-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agv', 's8_moved_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agv-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agv', 's9_downgraded_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-agv-1', 'a');
reset role;
update public.profiles set role = 'admin' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('agv', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-agv-1', 'b');
select pb.step('agv', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-agv-1', 'a');
reset role;
set td0149.boom = 'carrier_dispatch_service_agreement_idempotency';
set role authenticated;
select pb.step('agv', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-agv-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('agv', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-agv-3', 'a');
select pb.step('agv', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-agv-3', 'a');
reset role;

-- ---- apv: approve_carrier_dispatch_service_agreement_version (0145)
select pb.snap('apv');
set role authenticated;
select pb.step('apv', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-apv-1', 'a');
select pb.step('apv', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-apv-1', 'a');
select pb.step('apv', 's2_other_authorized_replay', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-apv-1', 'a');
select pb.step('apv', 's3_unauthenticated', null, '1', 'KEY-apv-1', 'a');
select pb.step('apv', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-apv-1', 'a');
select pb.step('apv', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-apv-1', 'a');
select pb.step('apv', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-apv-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('apv', 's7_removed_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-apv-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('apv', 's8_moved_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-apv-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('apv', 's9_downgraded_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-apv-1', 'a');
reset role;
update public.profiles set role = 'admin' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('apv', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-apv-1', 'b');
select pb.step('apv', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-apv-1', 'a');
reset role;
set td0149.boom = 'carrier_dispatch_service_agreement_idempotency';
set role authenticated;
select pb.step('apv', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-apv-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('apv', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-apv-3', 'a');
select pb.step('apv', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-apv-3', 'a');
reset role;

-- ---- dav: deactivate_carrier_dispatch_service_agreement_version (0145)
select pb.snap('dav');
set role authenticated;
select pb.step('dav', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-dav-1', 'a');
select pb.step('dav', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-dav-1', 'a');
select pb.step('dav', 's2_other_authorized_replay', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dav-1', 'a');
select pb.step('dav', 's3_unauthenticated', null, '1', 'KEY-dav-1', 'a');
select pb.step('dav', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-dav-1', 'a');
select pb.step('dav', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-dav-1', 'a');
select pb.step('dav', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-dav-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dav', 's7_removed_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dav-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dav', 's8_moved_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dav-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dav', 's9_downgraded_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dav-1', 'a');
reset role;
update public.profiles set role = 'admin' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dav', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-dav-1', 'b');
select pb.step('dav', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-dav-1', 'a');
reset role;
set td0149.boom = 'carrier_dispatch_service_agreement_idempotency';
set role authenticated;
select pb.step('dav', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-dav-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('dav', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-dav-3', 'a');
select pb.step('dav', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-dav-3', 'a');
reset role;

-- ---- dag: deactivate_carrier_dispatch_service_agreement (0145)
select pb.snap('dag');
set role authenticated;
select pb.step('dag', 's0_orig', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-dag-1', 'a');
select pb.step('dag', 's1_same_user_replay', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-dag-1', 'a');
select pb.step('dag', 's2_other_authorized_replay', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dag-1', 'a');
select pb.step('dag', 's3_unauthenticated', null, '1', 'KEY-dag-1', 'a');
select pb.step('dag', 's4_unauthorized_role', 'dddd0000-0000-0000-0000-000000000001', '1', 'KEY-dag-1', 'a');
select pb.step('dag', 's5_foreign_org_real_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-dag-1', 'a');
select pb.step('dag', 's6_foreign_org_wrong_key', 'bbbb0000-0000-0000-0000-000000000001', '1', 'KEY-dag-1-WRONG', 'a');
reset role;
update public.profiles set organization_id = null where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dag', 's7_removed_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dag-1', 'a');
reset role;
update public.profiles set organization_id = '22222222-2222-2222-2222-222222222222' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dag', 's8_moved_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dag-1', 'a');
reset role;
update public.profiles set organization_id = '11111111-1111-1111-1111-111111111111', role = 'viewer' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dag', 's9_downgraded_member', 'aaaa0000-0000-0000-0000-000000000002', '1', 'KEY-dag-1', 'a');
reset role;
update public.profiles set role = 'admin' where id = 'aaaa0000-0000-0000-0000-000000000002';
set role authenticated;
select pb.step('dag', 's10_changed_request', 'aaaa0000-0000-0000-0000-000000000001', '1', 'KEY-dag-1', 'b');
select pb.step('dag', 's11_same_key_other_target', 'aaaa0000-0000-0000-0000-000000000001', '2', 'KEY-dag-1', 'a');
reset role;
set td0149.boom = 'carrier_dispatch_service_agreement_idempotency';
set role authenticated;
select pb.step('dag', 's13_failed_tx', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-dag-3', 'a');
reset role;
set td0149.boom = '';
set role authenticated;
select pb.step('dag', 's14_retry_after_failure', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-dag-3', 'a');
select pb.step('dag', 's15_retry_replays', 'aaaa0000-0000-0000-0000-000000000001', '3', 'KEY-dag-3', 'a');
reset role;

\pset format unaligned
\pset tuples_only on
\pset fieldsep ''
select 'PROBE', kind, tag, outcome, msg, n_led, n_act, n_biz, biz from pb.rec order by seq;
