-- preflight.sql
-- PROPOSAL 0157 -- NOT APPROVED FOR PRODUCTION. NOT APPLIED. NOT A PRODUCTION MIGRATION. Sequencing: ... -> 0152 -> 0154 -> 0155 -> (0156 optional, superseded) -> 0157 (this); unrelated 0148 -> 0153 or 0158+. Finding F-08 (carrier invoices).
-- READ-ONLY: ONE select statement over catalogs and public tables; no data-/schema-changing statement, no transaction control. RESULT: every row INFO or PASS and a final RESULT | PASS row;
-- otherwise the statement RAISES (invalid input syntax for type integer: "PREFLIGHT 0157 FAIL ...") whose text is the complete report.
with rows as (
  select 100 as ord, 'SERVER' as section, 'server_version' as item, 'INFO' as result, current_setting('server_version')::text as detail
  union all select 110, 'PRECONDITION', 'proposal 0155 is applied (strict evidence + review table)', case when to_regprocedure('public.carrier_evidence_for_relationship(uuid)') is not null and to_regclass('public.carrier_inference_review_0155') is not null then 'PASS' else 'FAIL' end, 'catalog'
  union all select 111, 'PRECONDITION', 'carrier invoice tables and the readiness classifier exist', case when to_regclass('public.carrier_invoices') is not null and to_regclass('public.carrier_invoice_issuance_snapshots') is not null and to_regclass('public.carrier_invoice_line_items') is not null and to_regprocedure('public.classify_carrier_factoring_readiness(uuid,uuid,uuid)') is not null then 'PASS' else 'FAIL' end, 'catalog'
  union all select 112, 'PRECONDITION', 'no function with a 0157 name exists in ANY schema (no overload / twin)', case when not exists (select 1 from pg_proc p where p.proname in ('preview_carrier_invoice_factoring', 'submit_carrier_invoice_to_factor', 'withdraw_carrier_invoice_factoring_submission', 'set_carrier_factoring_submitter', 'preview_carrier_invoice_issuance', 'create_carrier_invoice_draft_from_loads', 'mark_carrier_invoice_ready_for_issue', 'discard_carrier_invoice_draft', 'issue_prepared_carrier_invoice', 'preview_carrier_invoice_reissue', 'reissue_carrier_invoice', 'verify_carrier_invoice_factoring_audit_chain_0157') or p.proname like '\_cif\_%' escape '\') then 'PASS' else 'FAIL' end, (select count(*)::text from pg_proc p where p.proname like '%carrier_invoice_to_factor%' or p.proname like '\_cif\_%' escape '\') || ' matching'
  union all select 113, 'PRECONDITION', 'no 0157 table exists yet', case when to_regclass('public.carrier_invoice_factoring_gate_0157') is null and to_regclass('public.carrier_factoring_submitter_grants_0157') is null and to_regclass('public.carrier_invoice_factoring_submissions_0157') is null and to_regclass('public.carrier_invoice_factoring_snapshots_0157') is null and to_regclass('public.carrier_invoice_factoring_audit_0157') is null and to_regclass('public.carrier_invoice_issuance_terms_0157') is null and to_regclass('public.carrier_invoice_workflow_ops_0157') is null and to_regclass('public.carrier_invoice_billable_ledger_0157') is null and to_regclass('public.carrier_invoice_reissues_0157') is null and to_regclass('public.carrier_invoice_dispatch_fee_links_0157') is null then 'PASS' else 'FAIL' end, 'catalog'
  union all select 114, 'PRECONDITION', 'the legacy 0156 gate (if installed) is DISABLED (D-08b)', case when to_regclass('public.factoring_submission_gate') is null then 'PASS' else case when (xpath('/row/e/text()', query_to_xml('select exists (select 1 from public.factoring_submission_gate where enabled) as e', false, true, '')))[1]::text = 'false' then 'PASS' else 'FAIL' end end, coalesce(to_regclass('public.factoring_submission_gate')::text, '0156 not installed')
  union all select 120, 'DATA (informational)', 'carrier_invoices total / issued / freight / dispatch-service', 'INFO', (select count(*)::text || ' / ' || count(*) filter (where issuance_status = 'issued')::text || ' / ' || count(*) filter (where invoice_document_type = 'carrier_freight_invoice')::text || ' / ' || count(*) filter (where invoice_document_type = 'dispatch_service_invoice')::text from public.carrier_invoices)
  union all select 121, 'DATA (informational)', 'factored carriers with 0 or 2+ active default relationships (their invoices would be refused: NO_ACTIVE_DEFAULT_RELATIONSHIP / MULTIPLE_DEFAULT_RELATIONSHIPS)', 'INFO', (select count(*)::text from public.carriers c where c.factoring_mode::text = 'factored' and (select count(*) from public.factoring_relationships r where r.carrier_id = c.id and r.is_default and r.is_active) <> 1)
  union all select 122, 'DATA (informational)', 'pending 0155 reviews / open factoring exception records (both must be 0 before the gate may be enabled: D-08i)', 'INFO', (select count(*)::text from public.carrier_inference_review_0155 where decision_status = 'pending' and classification <> 'supported') || ' / ' || (select count(*)::text from public.unresolved_carrier_records where status = 'unresolved' and record_type in ('factoring_relationship', 'factored_invoice'))
),
verdict as (
  select count(*) filter (where result = 'PASS') as n_pass, count(*) filter (where result = 'FAIL') as n_fail, count(*) filter (where result = 'INFO') as n_info,
         case when count(*) filter (where result = 'FAIL') = 0 and count(*) filter (where result = 'PASS') > 0 then 0
              else ('PREFLIGHT 0157 FAIL: ' || (count(*) filter (where result = 'FAIL'))::text || ' failing check(s). Full report follows.' || E'\n'
                    || string_agg(section || ' | ' || item || ' | ' || result || ' | ' || detail, E'\n' order by ord))::int
         end as gate
  from rows
)
select r.ord, r.section, r.item, r.result, r.detail from rows r cross join verdict v where v.gate = 0
union all
select 9000, 'RESULT', 'PREFLIGHT 0157: 0155 applied, no 0157 object, legacy gate disabled', 'PASS', v.n_pass::text || ' checks passed, 0 failed, ' || v.n_info::text || ' informational rows' from verdict v where v.gate = 0
order by 1;
