"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { FileCheck2, FileWarning, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/toast";
import { generateSetupPackage } from "../actions";
import type { SetupDocumentCandidate } from "@/lib/carrier-setup-packages/candidates";

type Application = { id: string; legal_name: string | null; dba_name: string | null; mc_number: string | null; dot_number: string | null };
type Broker = { id: string; company_name: string; contact_name: string | null; email: string | null };

export function PackageBuilder({ application, brokers, candidates }: { application: Application; brokers: Broker[]; candidates: SetupDocumentCandidate[] }) {
  const router = useRouter(); const toast = useToast(); const [pending, start] = useTransition();
  const [brokerId, setBrokerId] = useState(""); const [recipientName, setRecipientName] = useState(""); const [recipientEmail, setRecipientEmail] = useState("");
  const [selected, setSelected] = useState<string[]>(candidates.filter((c) => c.defaultSelected && c.documentId).map((c) => c.documentId!));
  const selectedCandidates = useMemo(() => candidates.filter((c) => c.documentId && selected.includes(c.documentId)), [candidates, selected]);
  const totalBytes = selectedCandidates.reduce((sum, c) => sum + (c.fileSizeBytes ?? 0), 0);
  function selectBroker(value: string) { setBrokerId(value); const broker = brokers.find((b) => b.id === value); if (broker) { setRecipientName(broker.contact_name ?? ""); setRecipientEmail(broker.email ?? ""); } }
  function generate() { start(async () => { const result = await generateSetupPackage(application.id, { brokerId: brokerId || null, recipientName, recipientEmail, documentIds: selected }); if (!result.ok) toast.show("error", result.error); else router.push(`/carriers/onboarding/${application.id}/setup-packages/${result.data.packageId}`); }); }
  return <div className="mx-auto w-full min-w-0 max-w-6xl space-y-4">
    <div className="flex min-w-0 flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-[12px] font-medium uppercase tracking-wide text-muted-foreground">Carrier Setup Package</p><h1 className="break-words text-xl font-semibold">{application.legal_name ?? "Carrier"}</h1><p className="break-words text-[13px] text-muted-foreground">{application.mc_number ? `MC ${application.mc_number}` : "MC -"} &nbsp; {application.dot_number ? `USDOT ${application.dot_number}` : "USDOT -"}</p></div><Link href={`/carriers/onboarding/${application.id}`} className="text-[13px] text-primary hover:underline">Back to application</Link></div>
    <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_300px]">
      <div className="min-w-0 space-y-4">
        <section className="min-w-0 max-w-full rounded-md border border-desktop-border bg-card p-4"><h2 className="text-[14px] font-semibold">Prepared For</h2><div className="mt-3 grid min-w-0 gap-3 sm:grid-cols-2"><label className="min-w-0 text-[12px] font-medium">Broker<select value={brokerId} onChange={(e) => selectBroker(e.target.value)} className="mt-1 h-8 w-full min-w-0 max-w-full rounded-sm border border-desktop-border bg-card px-2 text-[13px]"><option value="">Generic package</option>{brokers.map((b) => <option key={b.id} value={b.id}>{b.company_name}</option>)}</select></label><label className="min-w-0 text-[12px] font-medium">Recipient Name<input value={recipientName} onChange={(e) => setRecipientName(e.target.value)} className="mt-1 h-8 w-full min-w-0 max-w-full rounded-sm border border-desktop-border bg-card px-2 text-[13px]" /></label><label className="min-w-0 text-[12px] font-medium sm:col-span-2">Recipient Email<input type="email" value={recipientEmail} onChange={(e) => setRecipientEmail(e.target.value)} className="mt-1 h-8 w-full min-w-0 max-w-full rounded-sm border border-desktop-border bg-card px-2 text-[13px]" /></label></div></section>
        <section className="min-w-0 max-w-full rounded-md border border-desktop-border bg-card"><div className="border-b border-desktop-border p-4"><h2 className="text-[14px] font-semibold">Documents</h2><p className="break-words text-[12.5px] text-muted-foreground">Only verified, current, unexpired PDF/JPG/PNG files can be selected.</p></div><div className="min-w-0 divide-y divide-desktop-border">{candidates.map((candidate) => { const eligible = candidate.status === "eligible" && candidate.documentId; return <label key={candidate.candidateKey} className={`flex min-w-0 max-w-full gap-3 p-3.5 ${eligible ? "cursor-pointer" : "bg-muted/30"}`}><input type="checkbox" className="mt-1 size-4 shrink-0" checked={Boolean(candidate.documentId && selected.includes(candidate.documentId))} disabled={!eligible} onChange={() => candidate.documentId && setSelected((current) => current.includes(candidate.documentId!) ? current.filter((id) => id !== candidate.documentId) : [...current, candidate.documentId!])} /><span className="min-w-0 flex-1"><span className="flex min-w-0 items-start gap-1.5 break-words text-[13px] font-medium">{eligible ? <FileCheck2 className="size-4 shrink-0 text-success" /> : <FileWarning className="size-4 shrink-0 text-warning" />}<span className="min-w-0 break-words">{candidate.label}</span></span>{candidate.fileName && <span className="mt-0.5 block break-all text-[12px] text-muted-foreground" title={candidate.fileName}>{candidate.fileName}</span>}<span className={`mt-1 block break-words text-[11.5px] ${eligible ? "text-success" : "text-warning"}`}>{candidate.statusMessage}</span><span className="mt-0.5 block break-words text-[11px] text-muted-foreground">{candidate.uploadedAt ? `Uploaded ${new Date(candidate.uploadedAt).toLocaleDateString()}` : "Missing"}{candidate.expiryDate ? ` - Expires ${new Date(candidate.expiryDate + "T00:00:00").toLocaleDateString()}` : ""}</span></span></label>; })}</div></section>
      </div>
      <aside className="h-fit min-w-0 max-w-full rounded-md border border-desktop-border bg-card p-4 lg:sticky lg:top-4"><h2 className="text-[14px] font-semibold">Package Summary</h2><dl className="mt-3 space-y-2 text-[12.5px]"><div className="flex min-w-0 flex-wrap justify-between gap-x-2"><dt className="text-muted-foreground">Generated pages</dt><dd className="break-words text-right">Cover, contents, profile</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Source documents</dt><dd>{selected.length} / 12</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Source size</dt><dd>{(totalBytes / 1024 / 1024).toFixed(1)} MB / 40 MB</dd></div></dl><Button className="mt-4 w-full max-w-full" disabled={pending || selected.length < 1 || selected.length > 12 || totalBytes > 40 * 1024 * 1024} onClick={generate}>{pending && <Loader2 className="size-4 animate-spin" />}{pending ? "Generating..." : "Generate Setup Package"}</Button><p className="mt-2 break-words text-[11px] leading-relaxed text-muted-foreground">Generation creates a new immutable version. Later document changes require another package.</p></aside>
    </div>
  </div>;
}
