-- =============================================================================
-- 0116_quickbooks_oauth_foundation.sql
--
-- PRE-APPLY -- DO NOT APPLY WITHOUT MANUAL REVIEW.
--
-- Secure server-side persistence for a per-organization QuickBooks Online
-- OAuth 2.0 connection (SANDBOX/DEVELOPMENT phase). No invoice / customer /
-- payment sync is built here. It establishes ONLY:
--   * quickbooks_oauth_states  -- one-time, short-lived, user+org-bound CSRF
--                                 `state` values (authenticated RPCs)
--   * quickbooks_connections   -- the connection + ENCRYPTED access/refresh
--                                 tokens (bytea, pgp_sym_encrypt), one per org,
--                                 plus a token_generation counter for
--                                 optimistic concurrency on refresh
--   * app_encryption_keys row 'quickbooks_token_key' (generated here from the
--                                 DB CSPRNG -- never in source, never in env)
--   * SECURITY DEFINER RPCs. The two that only touch the CSRF state are
--     callable by `authenticated` (they need auth.uid()/current_org_id() to
--     bind + validate). EVERY RPC that encrypts, decrypts, rotates, or
--     returns a plaintext token is `service_role`-ONLY -- a signed-in
--     owner/admin browser/PostgREST session can NEVER pull a plaintext
--     QuickBooks token out of the database. Owner/admin authorization for
--     the user-facing Connect/Disconnect flows lives in the application
--     layer (server actions), which then call the service-role RPCs from
--     trusted server code with the caller's own org id.
--
-- Secrets-at-rest mirrors this schema's existing pattern exactly (driver
-- SSN/bank 0014/0019; carrier EIN 0081): pgcrypto pgp_sym_encrypt/decrypt,
-- key fetched via public.get_app_encryption_key() from
-- public.app_encryption_keys (columns key_name/key_value; no RLS policy;
-- unreachable via PostgREST). Encrypted columns are REVOKE'd from every
-- client role. Non-secret connection state (realm id, company name,
-- timestamps) is mirrored into the existing integration_settings row
-- (0008/0056) so the Integrations Center keeps working unchanged.
--
-- CONCURRENCY NOTE (Issue 1): a token refresh spans TWO separate Supabase
-- RPC round-trips with an external Intuit HTTP call in between. The first
-- RPC's transaction (and any FOR UPDATE lock) is already released by the
-- time the second RPC runs, so a row lock CANNOT serialize the whole
-- workflow. Concurrency safety here is OPTIMISTIC: get_quickbooks_refresh_
-- material() returns the current token_generation; refresh_quickbooks_
-- connection() only writes WHERE token_generation = <expected> and bumps it.
-- A refresh that raced and lost gets a STALE_REFRESH error and must reload
-- the (already-rotated) current credentials instead of overwriting them.
--
-- Nothing here modifies an existing table's data or an existing function.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PART 1 -- token encryption key. Generated ONCE, here, from the database's
-- own CSPRNG. Never printed, never committed, never an env var. Same shape
-- and same table (key_name/key_value) as driver_pii_key (0014) /
-- carrier_pii_key (0081).
-- -----------------------------------------------------------------------------
insert into public.app_encryption_keys (key_name, key_value)
values ('quickbooks_token_key', encode(gen_random_bytes(32), 'hex'))
on conflict (key_name) do nothing;

-- -----------------------------------------------------------------------------
-- PART 2 -- quickbooks_oauth_states: CSRF `state` for the authorization-code
-- flow. One row per "Connect QuickBooks" click, bound to the initiating
-- user AND organization, short TTL, single-use (consumed_at).
-- -----------------------------------------------------------------------------
create table public.quickbooks_oauth_states (
  id uuid primary key default gen_random_uuid(),
  -- Opaque, high-entropy value (>=32 random bytes, base64url) generated by
  -- the app and sent to Intuit as ?state=.
  state_token text not null unique check (length(state_token) between 32 and 512),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  -- The exact user who started the flow.
  created_by uuid not null references public.profiles (id) on delete cascade,
  -- Optional post-connect landing path. Only ever a site-relative path
  -- (validated '^/' and not '//') -- never an absolute URL.
  redirect_after text check (redirect_after is null or (redirect_after like '/%' and redirect_after not like '//%')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  constraint quickbooks_oauth_states_ttl_sane check (expires_at > created_at)
);

comment on table public.quickbooks_oauth_states is
  'One-time, short-lived (10 min) OAuth 2.0 CSRF `state` values for the QuickBooks connect flow. Bound to created_by + organization_id; validated against the live session and consumed exactly once by consume_quickbooks_oauth_state() during the callback. Rows are harmless after expiry (optional periodic DELETE could be added later -- no pg_cron job here).';

create index quickbooks_oauth_states_expiry_idx on public.quickbooks_oauth_states (expires_at);
create index quickbooks_oauth_states_org_idx on public.quickbooks_oauth_states (organization_id);

alter table public.quickbooks_oauth_states enable row level security;

-- Owner/admin, own-org SELECT only. INSERT/consume are SECURITY DEFINER.
create policy quickbooks_oauth_states_select on public.quickbooks_oauth_states
  for select using (
    organization_id = public.current_org_id()
    and public.has_role(array['owner', 'admin']::public.org_role[])
  );

-- -----------------------------------------------------------------------------
-- PART 3 -- quickbooks_connections: the connection + encrypted tokens.
-- One per organization (unique organization_id); realm_id globally unique
-- so one QuickBooks company can never bind to two TDP orgs.
-- -----------------------------------------------------------------------------
create table public.quickbooks_connections (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null unique references public.organizations (id) on delete cascade,
  -- Intuit's company/realm id. OPAQUE reference, NOT a credential -- also
  -- mirrored to integration_settings.external_account_id.
  realm_id text not null unique check (btrim(realm_id) <> ''),
  -- pgp_sym_encrypt(<token>, quickbooks_token_key). Present while
  -- status='connected'; NULLed on disconnect.
  access_token_encrypted bytea,
  refresh_token_encrypted bytea,
  access_token_expires_at timestamptz,
  -- Intuit refresh tokens are long-lived (~100 days) and rotate on use.
  refresh_token_expires_at timestamptz,
  scopes text not null default 'com.intuit.quickbooks.accounting',
  token_type text not null default 'bearer',
  -- Optimistic-concurrency guard for the two-round-trip refresh workflow.
  -- Every credential-mutating RPC bumps this; refresh writes only when the
  -- caller's expected value still matches.
  token_generation bigint not null default 0,
  -- Non-secret, from a CompanyInfo read. Mirrored to
  -- integration_settings.account_label.
  company_name text,
  status text not null default 'connected'
    check (status in ('connected', 'reconnect_required', 'disconnected')),
  -- While connected, both encrypted tokens + an access expiry must exist.
  constraint quickbooks_connections_token_shape check (
    status <> 'connected'
    or (access_token_encrypted is not null and refresh_token_encrypted is not null and access_token_expires_at is not null)
  ),
  last_refreshed_at timestamptz,
  last_error_code text,
  last_error_message text,
  connected_at timestamptz not null default now(),
  disconnected_at timestamptz,
  created_by uuid references public.profiles (id) on delete set null,
  updated_by uuid references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now()
);

comment on table public.quickbooks_connections is
  'Per-organization QuickBooks Online OAuth connection. access_token_encrypted / refresh_token_encrypted are pgp_sym_encrypt(..., quickbooks_token_key) and are REVOKE''d from anon/authenticated -- plaintext is reachable ONLY via the service_role-only SECURITY DEFINER RPCs in this migration. realm_id/company_name/timestamps are non-secret and mirrored into integration_settings. One row per org; realm_id globally unique; token_generation guards concurrent refreshes.';

comment on column public.quickbooks_connections.access_token_encrypted is
  'PGP-symmetric-encrypted (pgcrypto) with app_encryption_keys.quickbooks_token_key. Never selectable by anon/authenticated -- see the column-level REVOKE below. Decrypted ONLY inside get_quickbooks_access_material() (service_role only); rotated by store_quickbooks_connection()/refresh_quickbooks_connection() (service_role only).';

drop trigger if exists set_updated_at on public.quickbooks_connections;
create trigger set_updated_at before update on public.quickbooks_connections
  for each row execute function public.set_updated_at();

-- The encrypted token columns are not even selectable as ciphertext.
revoke select (access_token_encrypted, refresh_token_encrypted) on public.quickbooks_connections from authenticated, anon;

alter table public.quickbooks_connections enable row level security;

-- Owner/admin, own-org SELECT only (of the non-secret columns -- the two
-- bytea columns are already REVOKE'd). NO insert/update/delete policy for
-- authenticated: every write goes through a service_role-only RPC below
-- (same "RLS closed, RPC is the only writer" shape as carrier_w9s finalize,
-- 0099, and carrier_suspensions, 0102).
create policy quickbooks_connections_select on public.quickbooks_connections
  for select using (
    organization_id = public.current_org_id()
    and public.has_role(array['owner', 'admin']::public.org_role[])
  );

-- =============================================================================
-- PART 4 -- RPCs.
--
-- GROUP A (authenticated-callable): only touch the CSRF state, return NO
--   secret. They need auth.uid()/current_org_id() to bind + validate.
-- GROUP B (service_role-ONLY): encrypt / decrypt / rotate / return a
--   plaintext token, or are pure server-workflow steps. REVOKE'd from
--   authenticated + anon; granted only to service_role. Each takes an
--   explicit p_organization_id (service_role has no JWT, so current_org_id()
--   is null) which the trusted server supplies from the caller's own
--   authenticated session.
-- All are SECURITY DEFINER with an explicit search_path; none ever RAISE a
-- token value.
-- =============================================================================

-- ------------------------- GROUP A -- authenticated -------------------------

-- 4a. Create a one-time CSRF state for the current owner/admin user + org.
create or replace function public.create_quickbooks_oauth_state(p_state_token text, p_redirect_after text default null)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_org uuid := public.current_org_id();
  v_uid uuid := auth.uid();
begin
  if v_org is null or v_uid is null then
    raise exception 'No authenticated organization context.';
  end if;
  if not public.has_role(array['owner', 'admin']::public.org_role[]) then
    raise exception 'Only an owner or admin may connect QuickBooks.';
  end if;
  if p_state_token is null or length(p_state_token) < 32 then
    raise exception 'Invalid OAuth state token.';
  end if;
  if p_redirect_after is not null and (p_redirect_after not like '/%' or p_redirect_after like '//%') then
    raise exception 'redirect_after must be a site-relative path.';
  end if;

  insert into public.quickbooks_oauth_states (state_token, organization_id, created_by, redirect_after, expires_at)
  values (p_state_token, v_org, v_uid, p_redirect_after, now() + interval '10 minutes');
end;
$$;

-- 4b. Consume a state exactly once, ONLY for the session it was issued to.
-- A mismatched session is rejected WITHOUT burning the state (so a stolen
-- state_token cannot be used to DoS the real user's pending flow). Returns
-- the bound org/user so the callback can re-check them (defense in depth).
create or replace function public.consume_quickbooks_oauth_state(p_state_token text)
returns table (organization_id uuid, created_by uuid, redirect_after text)
language plpgsql security definer set search_path = public as $$
declare v_row public.quickbooks_oauth_states;
begin
  select * into v_row from public.quickbooks_oauth_states
  where state_token = p_state_token
  for update;

  if v_row.id is null then raise exception 'Unknown OAuth state.'; end if;
  if v_row.organization_id is distinct from public.current_org_id()
     or v_row.created_by is distinct from auth.uid() then
    raise exception 'OAuth state does not belong to this session.';
  end if;
  if v_row.consumed_at is not null then raise exception 'OAuth state already used.'; end if;
  if v_row.expires_at < now() then raise exception 'OAuth state expired.'; end if;

  update public.quickbooks_oauth_states set consumed_at = now() where id = v_row.id;

  organization_id := v_row.organization_id;
  created_by := v_row.created_by;
  redirect_after := v_row.redirect_after;
  return next;
end;
$$;

-- ------------------------- GROUP B -- service_role only -------------------------

create or replace function public._quickbooks_assert_service_role()
returns void language plpgsql security definer set search_path = public as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'This QuickBooks function is server-only.' using errcode = '42501';
  end if;
end;
$$;

-- 4c. Store (or fully rotate) the connection + tokens. UPSERT on
-- organization_id; bumps token_generation so any in-flight refresh loses.
-- Mirrors non-secret state into integration_settings. p_actor_id is the
-- authenticated owner/admin resolved by the trusted caller.
create or replace function public.store_quickbooks_connection(
  p_organization_id uuid,
  p_actor_id uuid,
  p_realm_id text,
  p_access_token text,
  p_refresh_token text,
  p_access_expires_at timestamptz,
  p_refresh_expires_at timestamptz,
  p_scopes text,
  p_company_name text
) returns void language plpgsql security definer set search_path = public, extensions as $$
declare
  v_key text := public.get_app_encryption_key('quickbooks_token_key');
  v_settings_id uuid;
  v_other_org uuid;
begin
  perform public._quickbooks_assert_service_role();
  if v_key is null then raise exception 'quickbooks_token_key is not configured.'; end if;
  if p_organization_id is null then raise exception 'organization id is required.'; end if;
  if coalesce(btrim(p_realm_id), '') = '' or coalesce(btrim(p_access_token), '') = '' or coalesce(btrim(p_refresh_token), '') = '' then
    raise exception 'Missing realm id or token material.';
  end if;

  -- A realm may bind to exactly one org.
  select organization_id into v_other_org from public.quickbooks_connections
  where realm_id = p_realm_id and organization_id <> p_organization_id;
  if v_other_org is not null then
    raise exception 'This QuickBooks company is already connected to a different organization.';
  end if;

  insert into public.quickbooks_connections (
    organization_id, realm_id, access_token_encrypted, refresh_token_encrypted,
    access_token_expires_at, refresh_token_expires_at, scopes, company_name,
    status, connected_at, disconnected_at, last_refreshed_at, last_error_code, last_error_message,
    created_by, updated_by
  ) values (
    p_organization_id, p_realm_id,
    pgp_sym_encrypt(p_access_token, v_key), pgp_sym_encrypt(p_refresh_token, v_key),
    p_access_expires_at, p_refresh_expires_at,
    coalesce(nullif(btrim(p_scopes), ''), 'com.intuit.quickbooks.accounting'),
    nullif(btrim(p_company_name), ''),
    'connected', now(), null, now(), null, null, p_actor_id, p_actor_id
  )
  on conflict (organization_id) do update set
    realm_id = excluded.realm_id,
    access_token_encrypted = excluded.access_token_encrypted,
    refresh_token_encrypted = excluded.refresh_token_encrypted,
    access_token_expires_at = excluded.access_token_expires_at,
    refresh_token_expires_at = excluded.refresh_token_expires_at,
    scopes = excluded.scopes,
    company_name = coalesce(excluded.company_name, public.quickbooks_connections.company_name),
    status = 'connected',
    disconnected_at = null,
    last_error_code = null,
    last_error_message = null,
    last_refreshed_at = now(),
    token_generation = public.quickbooks_connections.token_generation + 1,
    updated_by = p_actor_id;

  insert into public.integration_settings (organization_id, provider, is_enabled, created_by, updated_by)
  values (p_organization_id, 'quickbooks', true, p_actor_id, p_actor_id)
  on conflict (organization_id, provider) do update set
    is_enabled = true,
    updated_by = p_actor_id
  returning id into v_settings_id;

  update public.integration_settings set
    external_account_id = p_realm_id,
    account_label = coalesce(nullif(btrim(p_company_name), ''), account_label),
    last_connected_at = now(),
    disconnected_at = null,
    last_error_code = null,
    last_error_message = null
  where id = v_settings_id;

  perform public.log_activity('integration'::public.entity_type, v_settings_id, 'quickbooks_connected',
    jsonb_build_object('realm_id', p_realm_id), p_organization_id);
end;
$$;

-- 4d. Decrypted ACCESS token for an outbound API call. Server memory only.
create or replace function public.get_quickbooks_access_material(p_organization_id uuid)
returns table (access_token text, realm_id text, access_token_expires_at timestamptz, token_generation bigint, status text)
language plpgsql security definer set search_path = public, extensions as $$
declare v_row public.quickbooks_connections; v_key text := public.get_app_encryption_key('quickbooks_token_key');
begin
  perform public._quickbooks_assert_service_role();
  if p_organization_id is null then raise exception 'organization id is required.'; end if;
  select * into v_row from public.quickbooks_connections where organization_id = p_organization_id;
  if v_row.id is null then raise exception 'No QuickBooks connection for this organization.'; end if;
  access_token := case when v_row.access_token_encrypted is null then null else pgp_sym_decrypt(v_row.access_token_encrypted, v_key) end;
  realm_id := v_row.realm_id;
  access_token_expires_at := v_row.access_token_expires_at;
  token_generation := v_row.token_generation;
  status := v_row.status;
  return next;
end;
$$;

-- 4e. Decrypted REFRESH token + the current token_generation for the
-- optimistic-concurrency guard in refresh_quickbooks_connection().
create or replace function public.get_quickbooks_refresh_material(p_organization_id uuid)
returns table (refresh_token text, realm_id text, refresh_token_expires_at timestamptz, token_generation bigint)
language plpgsql security definer set search_path = public, extensions as $$
declare v_row public.quickbooks_connections; v_key text := public.get_app_encryption_key('quickbooks_token_key');
begin
  perform public._quickbooks_assert_service_role();
  if p_organization_id is null then raise exception 'organization id is required.'; end if;
  select * into v_row from public.quickbooks_connections where organization_id = p_organization_id;
  if v_row.id is null then raise exception 'No QuickBooks connection for this organization.'; end if;
  if v_row.status = 'disconnected' or v_row.refresh_token_encrypted is null then
    raise exception 'QuickBooks connection has no usable refresh token -- reconnect required.';
  end if;
  refresh_token := pgp_sym_decrypt(v_row.refresh_token_encrypted, v_key);
  realm_id := v_row.realm_id;
  refresh_token_expires_at := v_row.refresh_token_expires_at;
  token_generation := v_row.token_generation;
  return next;
end;
$$;

-- 4f. Store rotated tokens after a successful Intuit refresh -- OPTIMISTIC:
-- writes ONLY when token_generation still equals what the caller read in
-- 4e. If it changed (a concurrent refresh or a reconnect won), this raises
-- STALE_REFRESH and the caller must reload current credentials rather than
-- overwrite the newer rotation.
create or replace function public.refresh_quickbooks_connection(
  p_organization_id uuid,
  p_expected_generation bigint,
  p_new_access_token text,
  p_new_refresh_token text,
  p_access_expires_at timestamptz,
  p_refresh_expires_at timestamptz
) returns void language plpgsql security definer set search_path = public, extensions as $$
declare v_key text := public.get_app_encryption_key('quickbooks_token_key');
begin
  perform public._quickbooks_assert_service_role();
  if p_organization_id is null then raise exception 'organization id is required.'; end if;

  update public.quickbooks_connections set
    access_token_encrypted = pgp_sym_encrypt(p_new_access_token, v_key),
    refresh_token_encrypted = pgp_sym_encrypt(
      coalesce(nullif(btrim(p_new_refresh_token), ''), pgp_sym_decrypt(refresh_token_encrypted, v_key)), v_key),
    access_token_expires_at = p_access_expires_at,
    refresh_token_expires_at = coalesce(p_refresh_expires_at, refresh_token_expires_at),
    status = 'connected',
    last_refreshed_at = now(),
    token_generation = token_generation + 1,
    last_error_code = null,
    last_error_message = null
  where organization_id = p_organization_id
    and token_generation = p_expected_generation
    and status <> 'disconnected';

  if not found then
    raise exception 'STALE_REFRESH: the QuickBooks token was rotated by another request; reload current credentials.'
      using errcode = 'P0001';
  end if;
end;
$$;

-- 4g. Mark the connection as needing re-authorization (Intuit invalid_grant
-- on refresh). Does not delete tokens; flips status + mirrors an error.
create or replace function public.mark_quickbooks_reconnect_required(p_organization_id uuid, p_code text, p_message text)
returns void language plpgsql security definer set search_path = public as $$
declare v_settings_id uuid;
begin
  perform public._quickbooks_assert_service_role();
  if p_organization_id is null then raise exception 'organization id is required.'; end if;

  update public.quickbooks_connections set
    status = 'reconnect_required',
    token_generation = token_generation + 1,
    last_error_code = nullif(btrim(coalesce(p_code, '')), ''),
    last_error_message = left(nullif(btrim(coalesce(p_message, '')), ''), 500)
  where organization_id = p_organization_id;

  select id into v_settings_id from public.integration_settings where organization_id = p_organization_id and provider = 'quickbooks';
  if v_settings_id is not null then
    update public.integration_settings set
      last_test_status = 'failure',
      last_error_code = 'REAUTH_REQUIRED',
      last_error_message = 'QuickBooks authorization expired or was revoked -- reconnect required.'
    where id = v_settings_id;
    perform public.log_activity('integration'::public.entity_type, v_settings_id, 'quickbooks_reconnect_required', null, p_organization_id);
  end if;
end;
$$;

-- 4h. Record the read-only CompanyInfo validation result.
create or replace function public.record_quickbooks_test_result(p_organization_id uuid, p_ok boolean, p_message text)
returns void language plpgsql security definer set search_path = public as $$
declare v_settings_id uuid;
begin
  perform public._quickbooks_assert_service_role();
  if p_organization_id is null then raise exception 'organization id is required.'; end if;
  select id into v_settings_id from public.integration_settings where organization_id = p_organization_id and provider = 'quickbooks';
  if v_settings_id is null then return; end if;
  update public.integration_settings set
    last_tested_at = now(),
    last_test_status = case when p_ok then 'success' else 'failure' end,
    last_test_message = left(coalesce(p_message, ''), 500),
    last_error_code = case when p_ok then null else 'TEST_FAILED' end,
    last_error_message = case when p_ok then null else left(coalesce(p_message, ''), 500) end
  where id = v_settings_id;
  perform public.log_activity('integration'::public.entity_type, v_settings_id,
    case when p_ok then 'connection_test_succeeded' else 'connection_test_failed' end,
    jsonb_build_object('provider', 'quickbooks'), p_organization_id);
end;
$$;

-- 4i. Disconnect. Returns the decrypted refresh token ONCE so the trusted
-- server can revoke it at Intuit, then NULLs both encrypted columns, flips
-- status, bumps generation, and mirrors the disconnect.
create or replace function public.disconnect_quickbooks_connection(p_organization_id uuid)
returns table (refresh_token text)
language plpgsql security definer set search_path = public, extensions as $$
declare v_row public.quickbooks_connections; v_key text := public.get_app_encryption_key('quickbooks_token_key'); v_settings_id uuid;
begin
  perform public._quickbooks_assert_service_role();
  if p_organization_id is null then raise exception 'organization id is required.'; end if;
  select * into v_row from public.quickbooks_connections where organization_id = p_organization_id for update;
  if v_row.id is null then raise exception 'No QuickBooks connection for this organization.'; end if;

  refresh_token := case when v_row.refresh_token_encrypted is null then null else pgp_sym_decrypt(v_row.refresh_token_encrypted, v_key) end;

  update public.quickbooks_connections set
    status = 'disconnected',
    disconnected_at = now(),
    access_token_encrypted = null,
    refresh_token_encrypted = null,
    access_token_expires_at = null,
    token_generation = token_generation + 1
  where id = v_row.id;

  select id into v_settings_id from public.integration_settings where organization_id = p_organization_id and provider = 'quickbooks';
  if v_settings_id is not null then
    update public.integration_settings set
      is_enabled = false,
      disconnected_at = now(),
      account_label = null,
      external_account_id = null
    where id = v_settings_id;
    perform public.log_activity('integration'::public.entity_type, v_settings_id, 'quickbooks_disconnected', null, p_organization_id);
  end if;

  return next;
end;
$$;

-- -----------------------------------------------------------------------------
-- PART 5 -- EXECUTE grants.
--   Group A (state only, no secret returned): authenticated.
--   Group B (touch plaintext tokens / server workflow): service_role ONLY.
--   Internal assertion helper: no client role.
-- -----------------------------------------------------------------------------
revoke execute on function public.create_quickbooks_oauth_state(text, text) from public, anon;
revoke execute on function public.consume_quickbooks_oauth_state(text) from public, anon;
grant execute on function public.create_quickbooks_oauth_state(text, text) to authenticated;
grant execute on function public.consume_quickbooks_oauth_state(text) to authenticated;

revoke execute on function public.store_quickbooks_connection(uuid, uuid, text, text, text, timestamptz, timestamptz, text, text) from public, anon, authenticated;
revoke execute on function public.get_quickbooks_access_material(uuid) from public, anon, authenticated;
revoke execute on function public.get_quickbooks_refresh_material(uuid) from public, anon, authenticated;
revoke execute on function public.refresh_quickbooks_connection(uuid, bigint, text, text, timestamptz, timestamptz) from public, anon, authenticated;
revoke execute on function public.mark_quickbooks_reconnect_required(uuid, text, text) from public, anon, authenticated;
revoke execute on function public.record_quickbooks_test_result(uuid, boolean, text) from public, anon, authenticated;
revoke execute on function public.disconnect_quickbooks_connection(uuid) from public, anon, authenticated;

grant execute on function public.store_quickbooks_connection(uuid, uuid, text, text, text, timestamptz, timestamptz, text, text) to service_role;
grant execute on function public.get_quickbooks_access_material(uuid) to service_role;
grant execute on function public.get_quickbooks_refresh_material(uuid) to service_role;
grant execute on function public.refresh_quickbooks_connection(uuid, bigint, text, text, timestamptz, timestamptz) to service_role;
grant execute on function public.mark_quickbooks_reconnect_required(uuid, text, text) to service_role;
grant execute on function public.record_quickbooks_test_result(uuid, boolean, text) to service_role;
grant execute on function public.disconnect_quickbooks_connection(uuid) to service_role;

revoke execute on function public._quickbooks_assert_service_role() from public, anon, authenticated;
